<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Regression and correlation | Welcome!</title>
  <meta name="description" content="Course notes for PSYC 3290" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Regression and correlation | Welcome!" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course notes for PSYC 3290" />
  <meta name="github-repo" content="dstanley4/psyc3290bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Regression and correlation | Welcome!" />
  
  <meta name="twitter:description" content="Course notes for PSYC 3290" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2023-09-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="an-emphasis-on-workflow.html"/>
<link rel="next" href="multiple-regression.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<script src="libs/htmlwidgets/htmlwidgets.js"></script>
<script src="libs/plotly-binding/plotly.js"></script>
<script src="libs/typedarray/typedarray.min.js"></script>
<link href="libs/crosstalk/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course:</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#software-choice"><i class="fa fa-check"></i><b>1.3</b> Software Choice</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#mac"><i class="fa fa-check"></i><b>1.3.1</b> Mac</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#pc"><i class="fa fa-check"></i><b>1.3.2</b> PC</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#run-rstudio-not-r"><i class="fa fa-check"></i><b>1.4</b> Run RStudio not R</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#rstudio-configuration-first-run-only"><i class="fa fa-check"></i><b>1.5</b> RStudio configuration, First run only</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#begin-with-an-rstudio-project"><i class="fa fa-check"></i><b>1.6</b> Begin with an RStudio Project</a></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.7</b> Exploring the R Studio Interface</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#console-panel"><i class="fa fa-check"></i><b>1.7.1</b> Console panel</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction.html"><a href="introduction.html#script-panel"><i class="fa fa-check"></i><b>1.7.2</b> Script Panel</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.8</b> Writing your first script</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="introduction.html"><a href="introduction.html#create-the-script-file"><i class="fa fa-check"></i><b>1.8.1</b> Create the script file</a></li>
<li class="chapter" data-level="1.8.2" data-path="introduction.html"><a href="introduction.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.8.2</b> Add a comment to your script</a></li>
<li class="chapter" data-level="1.8.3" data-path="introduction.html"><a href="introduction.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.8.3</b> Background about the tidyverse</a></li>
<li class="chapter" data-level="1.8.4" data-path="introduction.html"><a href="introduction.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.8.4</b> Add library(tidyverse) to your script</a></li>
<li class="chapter" data-level="1.8.5" data-path="introduction.html"><a href="introduction.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.8.5</b> Activate tidyverse auto-complete for your script</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#loading-your-data"><i class="fa fa-check"></i><b>1.9</b> Loading your data</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.9.1</b> Use read_csv (not read.csv) to open files.</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.10</b> Checking out your data</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="introduction.html"><a href="introduction.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.10.1</b> view(): See a spreadsheet view of your data</a></li>
<li class="chapter" data-level="1.10.2" data-path="introduction.html"><a href="introduction.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.10.2</b> print(): See you data in the Console</a></li>
<li class="chapter" data-level="1.10.3" data-path="introduction.html"><a href="introduction.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.3</b> head(): Check out the first few rows of data</a></li>
<li class="chapter" data-level="1.10.4" data-path="introduction.html"><a href="introduction.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.4</b> tail(): Check out the last few rows of data</a></li>
<li class="chapter" data-level="1.10.5" data-path="introduction.html"><a href="introduction.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.10.5</b> summary(): Quick summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="introduction.html"><a href="introduction.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.11</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="introduction.html"><a href="introduction.html#run-select-text"><i class="fa fa-check"></i><b>1.11.1</b> Run select text</a></li>
<li class="chapter" data-level="1.11.2" data-path="introduction.html"><a href="introduction.html#source-without-echo"><i class="fa fa-check"></i><b>1.11.2</b> Source (without Echo)</a></li>
<li class="chapter" data-level="1.11.3" data-path="introduction.html"><a href="introduction.html#source-with-echo"><i class="fa fa-check"></i><b>1.11.3</b> Source with Echo</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="introduction.html"><a href="introduction.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.12</b> Trying Source with Echo</a></li>
<li class="chapter" data-level="1.13" data-path="introduction.html"><a href="introduction.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.13</b> A few key points about</a>
<ul>
<li class="chapter" data-level="1.13.1" data-path="introduction.html"><a href="introduction.html#lists"><i class="fa fa-check"></i><b>1.13.1</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="introduction.html"><a href="introduction.html#revisiting-read_csv"><i class="fa fa-check"></i><b>1.14</b> Revisiting read_csv()</a></li>
<li class="chapter" data-level="1.15" data-path="introduction.html"><a href="introduction.html#thats-it"><i class="fa fa-check"></i><b>1.15</b> That’s it!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required</a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective</a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console</a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tidyverse-help-with-the-introverse"><i class="fa fa-check"></i><b>2.4</b> Tidyverse help with the Introverse</a></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Basic tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.5.1</b> select()</a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.5.2</b> summarise()</a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.5.3</b> filter()</a></li>
<li class="chapter" data-level="2.5.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.5.4</b> group_by()</a></li>
<li class="chapter" data-level="2.5.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.5.5</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.6</b> Advanced tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.6.1</b> select()</a></li>
<li class="chapter" data-level="2.6.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.6.2</b> summarise()</a></li>
<li class="chapter" data-level="2.6.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.6.3</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.7</b> Using help</a></li>
<li class="chapter" data-level="2.8" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.8</b> Base R vs tidyverse</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.8.1</b> Tibbles vs. data frames</a></li>
<li class="chapter" data-level="2.8.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.8.2</b> read.csv() and data frames</a></li>
<li class="chapter" data-level="2.8.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.8.3</b> read_csv() and tibbles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>3</b> Graphing</a>
<ul>
<li class="chapter" data-level="3.1" data-path="graphing.html"><a href="graphing.html#required-1"><i class="fa fa-check"></i><b>3.1</b> Required</a></li>
<li class="chapter" data-level="3.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>3.2</b> Data</a></li>
<li class="chapter" data-level="3.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>3.3</b> Graph basics</a></li>
<li class="chapter" data-level="3.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>3.4</b> Graphing efficiently</a></li>
<li class="chapter" data-level="3.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>3.5</b> Aesthetics</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>3.5.1</b> Fill color</a></li>
<li class="chapter" data-level="3.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>3.5.2</b> Overriding aes()</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>3.6</b> APA style</a></li>
<li class="chapter" data-level="3.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>3.7</b> Axes</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>3.7.1</b> Range</a></li>
<li class="chapter" data-level="3.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>3.7.2</b> Ticks</a></li>
<li class="chapter" data-level="3.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>3.7.3</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>3.8</b> Axis values</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>3.8.1</b> Text</a></li>
<li class="chapter" data-level="3.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>3.8.2</b> Angle</a></li>
<li class="chapter" data-level="3.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>3.8.3</b> Alignment</a></li>
<li class="chapter" data-level="3.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>3.8.4</b> Order</a></li>
<li class="chapter" data-level="3.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>3.8.5</b> Legend order</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>3.9</b> Custom colours</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>3.9.1</b> R palette</a></li>
<li class="chapter" data-level="3.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>3.9.2</b> Hex colours</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>3.10</b> Emoji</a></li>
<li class="chapter" data-level="3.11" data-path="graphing.html"><a href="graphing.html#accessible-colors"><i class="fa fa-check"></i><b>3.11</b> Accessible Colors</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="graphing.html"><a href="graphing.html#rcolorbrewer"><i class="fa fa-check"></i><b>3.11.1</b> RColorBrewer</a></li>
<li class="chapter" data-level="3.11.2" data-path="graphing.html"><a href="graphing.html#avoid-color"><i class="fa fa-check"></i><b>3.11.2</b> Avoid color</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>3.12</b> Saving</a>
<ul>
<li class="chapter" data-level="3.12.1" data-path="graphing.html"><a href="graphing.html#mac-1"><i class="fa fa-check"></i><b>3.12.1</b> MAC</a></li>
<li class="chapter" data-level="3.12.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>3.12.2</b> PC or MAC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="populations.html"><a href="populations.html"><i class="fa fa-check"></i><b>4</b> Populations</a>
<ul>
<li class="chapter" data-level="4.1" data-path="populations.html"><a href="populations.html#notation"><i class="fa fa-check"></i><b>4.1</b> Notation</a></li>
<li class="chapter" data-level="4.2" data-path="populations.html"><a href="populations.html#population-vs-samples"><i class="fa fa-check"></i><b>4.2</b> Population vs samples</a></li>
<li class="chapter" data-level="4.3" data-path="populations.html"><a href="populations.html#a-small-population"><i class="fa fa-check"></i><b>4.3</b> A small population</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="populations.html"><a href="populations.html#mean-mu"><i class="fa fa-check"></i><b>4.3.1</b> Mean (<span class="math inline">\(\mu\)</span>)</a></li>
<li class="chapter" data-level="4.3.2" data-path="populations.html"><a href="populations.html#variance-sigma2"><i class="fa fa-check"></i><b>4.3.2</b> Variance (<span class="math inline">\(\sigma^2\)</span>)</a></li>
<li class="chapter" data-level="4.3.3" data-path="populations.html"><a href="populations.html#standard-deviation-sigma"><i class="fa fa-check"></i><b>4.3.3</b> Standard Deviation (<span class="math inline">\(\sigma\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="populations.html"><a href="populations.html#visualizing-populations"><i class="fa fa-check"></i><b>4.4</b> Visualizing populations</a></li>
<li class="chapter" data-level="4.5" data-path="populations.html"><a href="populations.html#comparisons-same-sigma"><i class="fa fa-check"></i><b>4.5</b> Comparisons: Same <span class="math inline">\(\sigma\)</span></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="populations.html"><a href="populations.html#standardized-units"><i class="fa fa-check"></i><b>4.5.1</b> Standardized units</a></li>
<li class="chapter" data-level="4.5.2" data-path="populations.html"><a href="populations.html#cohens-d-units"><i class="fa fa-check"></i><b>4.5.2</b> Cohen’s <span class="math inline">\(d\)</span> units</a></li>
<li class="chapter" data-level="4.5.3" data-path="populations.html"><a href="populations.html#cohens-d-advantages"><i class="fa fa-check"></i><b>4.5.3</b> Cohen’s <span class="math inline">\(d\)</span> advantages</a></li>
<li class="chapter" data-level="4.5.4" data-path="populations.html"><a href="populations.html#cohens-d-caveats"><i class="fa fa-check"></i><b>4.5.4</b> Cohen’s <span class="math inline">\(d\)</span> caveats</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="populations.html"><a href="populations.html#comparisons-different-sigma"><i class="fa fa-check"></i><b>4.6</b> Comparisons: Different <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="4.7" data-path="populations.html"><a href="populations.html#comparisons-repeated-measures"><i class="fa fa-check"></i><b>4.7</b> Comparisons: Repeated Measures</a></li>
<li class="chapter" data-level="4.8" data-path="populations.html"><a href="populations.html#comparison-benchmarks"><i class="fa fa-check"></i><b>4.8</b> Comparison Benchmarks</a></li>
<li class="chapter" data-level="4.9" data-path="populations.html"><a href="populations.html#population-relations"><i class="fa fa-check"></i><b>4.9</b> Population relations</a></li>
<li class="chapter" data-level="4.10" data-path="populations.html"><a href="populations.html#relation-benchmarks"><i class="fa fa-check"></i><b>4.10</b> Relation benchmarks</a></li>
<li class="chapter" data-level="4.11" data-path="populations.html"><a href="populations.html#key-points"><i class="fa fa-check"></i><b>4.11</b> Key points</a></li>
<li class="chapter" data-level="4.12" data-path="populations.html"><a href="populations.html#minor-points"><i class="fa fa-check"></i><b>4.12</b> Minor Points</a></li>
<li class="chapter" data-level="4.13" data-path="populations.html"><a href="populations.html#self-assessment"><i class="fa fa-check"></i><b>4.13</b> Self Assessment</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html"><i class="fa fa-check"></i><b>5</b> Sampling Accuracy</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#data-for-the-chapter"><i class="fa fa-check"></i><b>5.2</b> Data for the chapter</a></li>
<li class="chapter" data-level="5.3" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#notation-1"><i class="fa fa-check"></i><b>5.3</b> Notation</a></li>
<li class="chapter" data-level="5.4" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-mu"><i class="fa fa-check"></i><b>5.4</b> Estimating <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias"><i class="fa fa-check"></i><b>5.4.1</b> Assessing bias</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-sigma2"><i class="fa fa-check"></i><b>5.5</b> Estimating <span class="math inline">\(\sigma^2\)</span></a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias-1"><i class="fa fa-check"></i><b>5.5.1</b> Assessing bias</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-sigma"><i class="fa fa-check"></i><b>5.6</b> Estimating <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="5.7" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-delta"><i class="fa fa-check"></i><b>5.7</b> Estimating <span class="math inline">\(\delta\)</span></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#pooled-standard-deviation"><i class="fa fa-check"></i><b>5.7.1</b> Pooled standard deviation</a></li>
<li class="chapter" data-level="5.7.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#calculating-d"><i class="fa fa-check"></i><b>5.7.2</b> Calculating <span class="math inline">\(d\)</span></a></li>
<li class="chapter" data-level="5.7.3" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias-2"><i class="fa fa-check"></i><b>5.7.3</b> Assessing bias</a></li>
<li class="chapter" data-level="5.7.4" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#illustrating-variability"><i class="fa fa-check"></i><b>5.7.4</b> Illustrating variability</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-rho"><i class="fa fa-check"></i><b>5.8</b> Estimating <span class="math inline">\(\rho\)</span></a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias-3"><i class="fa fa-check"></i><b>5.8.1</b> Assessing bias</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview-1"><i class="fa fa-check"></i><b>5.9</b> Overview</a></li>
<li class="chapter" data-level="5.10" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#meta-analysis"><i class="fa fa-check"></i><b>5.10</b> Meta-analysis</a></li>
<li class="chapter" data-level="5.11" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#a-joke"><i class="fa fa-check"></i><b>5.11</b> A joke</a></li>
<li class="chapter" data-level="5.12" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#key-points-1"><i class="fa fa-check"></i><b>5.12</b> Key Points</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling-precision.html"><a href="sampling-precision.html"><i class="fa fa-check"></i><b>6</b> Sampling Precision</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sampling-precision.html"><a href="sampling-precision.html#overview-2"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="sampling-precision.html"><a href="sampling-precision.html#population-individuals"><i class="fa fa-check"></i><b>6.2</b> Population / Individuals</a></li>
<li class="chapter" data-level="6.3" data-path="sampling-precision.html"><a href="sampling-precision.html#sampling-distribution"><i class="fa fa-check"></i><b>6.3</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.4" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-indices"><i class="fa fa-check"></i><b>6.4</b> Precision indices</a></li>
<li class="chapter" data-level="6.5" data-path="sampling-precision.html"><a href="sampling-precision.html#a-short-cut"><i class="fa fa-check"></i><b>6.5</b> A short cut</a></li>
<li class="chapter" data-level="6.6" data-path="sampling-precision.html"><a href="sampling-precision.html#estimates-of-precision"><i class="fa fa-check"></i><b>6.6</b> Estimates of precision</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="sampling-precision.html"><a href="sampling-precision.html#a-worked-example"><i class="fa fa-check"></i><b>6.6.1</b> A worked example</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="sampling-precision.html"><a href="sampling-precision.html#bias-of-precision-estimates"><i class="fa fa-check"></i><b>6.7</b> Bias of precision estimates</a></li>
<li class="chapter" data-level="6.8" data-path="sampling-precision.html"><a href="sampling-precision.html#where-are-we"><i class="fa fa-check"></i><b>6.8</b> Where are we?</a></li>
<li class="chapter" data-level="6.9" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-for-means-causes"><i class="fa fa-check"></i><b>6.9</b> Precision for means: Causes</a></li>
<li class="chapter" data-level="6.10" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-for-d-values-causes"><i class="fa fa-check"></i><b>6.10</b> Precision for <span class="math inline">\(d\)</span>-values: Causes</a>
<ul>
<li class="chapter" data-level="6.10.1" data-path="sampling-precision.html"><a href="sampling-precision.html#sample-size"><i class="fa fa-check"></i><b>6.10.1</b> Sample size</a></li>
<li class="chapter" data-level="6.10.2" data-path="sampling-precision.html"><a href="sampling-precision.html#population-effect-size-delta"><i class="fa fa-check"></i><b>6.10.2</b> Population effect size (<span class="math inline">\(\delta\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-for-sample-correlations-r-causes"><i class="fa fa-check"></i><b>6.11</b> Precision for sample correlations (<span class="math inline">\(r\)</span>): Causes</a>
<ul>
<li class="chapter" data-level="6.11.1" data-path="sampling-precision.html"><a href="sampling-precision.html#sample-size-1"><i class="fa fa-check"></i><b>6.11.1</b> Sample size</a></li>
<li class="chapter" data-level="6.11.2" data-path="sampling-precision.html"><a href="sampling-precision.html#population-effect-size-rho"><i class="fa fa-check"></i><b>6.11.2</b> Population effect size (<span class="math inline">\(\rho\)</span>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html"><i class="fa fa-check"></i><b>7</b> An Emphasis on Workflow</a>
<ul>
<li class="chapter" data-level="7.1" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#required-packages"><i class="fa fa-check"></i><b>7.1</b> Required Packages</a></li>
<li class="chapter" data-level="7.2" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#objective-1"><i class="fa fa-check"></i><b>7.2</b> Objective</a></li>
<li class="chapter" data-level="7.3" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#begin-with-the-end-in-mind"><i class="fa fa-check"></i><b>7.3</b> Begin with the end in mind</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#structuring-data-obtaining-tidy-data"><i class="fa fa-check"></i><b>7.3.1</b> Structuring data: Obtaining tidy data</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#data-collection-considerations"><i class="fa fa-check"></i><b>7.4</b> Data collection considerations</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#file-naming-conventions"><i class="fa fa-check"></i><b>7.4.1</b> File naming conventions</a></li>
<li class="chapter" data-level="7.4.2" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#data-column-naming-conventions"><i class="fa fa-check"></i><b>7.4.2</b> Data column naming conventions</a></li>
<li class="chapter" data-level="7.4.3" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#likert-type-items"><i class="fa fa-check"></i><b>7.4.3</b> Likert-type items</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#example-single-occassion-survey"><i class="fa fa-check"></i><b>7.5</b> Example: Single Occassion Survey</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#creating-factors"><i class="fa fa-check"></i><b>7.5.1</b> Creating factors</a></li>
<li class="chapter" data-level="7.5.2" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#factor-screening"><i class="fa fa-check"></i><b>7.5.2</b> Factor screening</a></li>
<li class="chapter" data-level="7.5.3" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#numeric-screening"><i class="fa fa-check"></i><b>7.5.3</b> Numeric screening</a></li>
<li class="chapter" data-level="7.5.4" data-path="an-emphasis-on-workflow.html"><a href="an-emphasis-on-workflow.html#scale-scores"><i class="fa fa-check"></i><b>7.5.4</b> Scale scores</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>8</b> Regression and correlation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#population-example"><i class="fa fa-check"></i><b>8.1</b> Population example</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#no-predictor"><i class="fa fa-check"></i><b>8.1.1</b> No predictor</a></li>
<li class="chapter" data-level="8.1.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#weak-relation"><i class="fa fa-check"></i><b>8.1.2</b> Weak relation</a></li>
<li class="chapter" data-level="8.1.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#strong-relation"><i class="fa fa-check"></i><b>8.1.3</b> Strong relation</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#consider-a-sample"><i class="fa fa-check"></i><b>8.2</b> Consider a sample</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#regression"><i class="fa fa-check"></i><b>8.2.1</b> Regression</a></li>
<li class="chapter" data-level="8.2.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation"><i class="fa fa-check"></i><b>8.2.2</b> Correlation</a></li>
<li class="chapter" data-level="8.2.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#graphing-1"><i class="fa fa-check"></i><b>8.2.3</b> Graphing</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#comparing-correlations"><i class="fa fa-check"></i><b>8.3</b> Comparing correlations</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#p-values"><i class="fa fa-check"></i><b>8.3.1</b> p-values</a></li>
<li class="chapter" data-level="8.3.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#within-a-data-set"><i class="fa fa-check"></i><b>8.3.2</b> Within a data set</a></li>
<li class="chapter" data-level="8.3.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#between-data-sets"><i class="fa fa-check"></i><b>8.3.3</b> Between data sets</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>9</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="multiple-regression.html"><a href="multiple-regression.html#overview-3"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="multiple-regression.html"><a href="multiple-regression.html#example"><i class="fa fa-check"></i><b>9.2</b> Example</a></li>
<li class="chapter" data-level="9.3" data-path="multiple-regression.html"><a href="multiple-regression.html#load-the-data"><i class="fa fa-check"></i><b>9.3</b> Load the data</a></li>
<li class="chapter" data-level="9.4" data-path="multiple-regression.html"><a href="multiple-regression.html#bivariate-relations"><i class="fa fa-check"></i><b>9.4</b> Bivariate relations</a></li>
<li class="chapter" data-level="9.5" data-path="multiple-regression.html"><a href="multiple-regression.html#single-best-predictor"><i class="fa fa-check"></i><b>9.5</b> Single best predictor</a></li>
<li class="chapter" data-level="9.6" data-path="multiple-regression.html"><a href="multiple-regression.html#multiple-regression-1"><i class="fa fa-check"></i><b>9.6</b> Multiple regression</a></li>
<li class="chapter" data-level="9.7" data-path="multiple-regression.html"><a href="multiple-regression.html#b-weights"><i class="fa fa-check"></i><b>9.7</b> <em>b</em>-weights</a></li>
<li class="chapter" data-level="9.8" data-path="multiple-regression.html"><a href="multiple-regression.html#r2"><i class="fa fa-check"></i><b>9.8</b> <span class="math inline">\(R^2\)</span></a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="multiple-regression.html"><a href="multiple-regression.html#method-1-ratio-approach"><i class="fa fa-check"></i><b>9.8.1</b> Method 1: Ratio Approach</a></li>
<li class="chapter" data-level="9.8.2" data-path="multiple-regression.html"><a href="multiple-regression.html#method-2-correlation-approach"><i class="fa fa-check"></i><b>9.8.2</b> Method 2: Correlation Approach</a></li>
<li class="chapter" data-level="9.8.3" data-path="multiple-regression.html"><a href="multiple-regression.html#r2-in-practice"><i class="fa fa-check"></i><b>9.8.3</b> <span class="math inline">\(R^2\)</span> in practice</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="multiple-regression.html"><a href="multiple-regression.html#semi-partial-sr"><i class="fa fa-check"></i><b>9.9</b> Semi-partial (<span class="math inline">\(sr\)</span>)</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="multiple-regression.html"><a href="multiple-regression.html#sr2-in-theory"><i class="fa fa-check"></i><b>9.9.1</b> <span class="math inline">\(sr^2\)</span> in theory</a></li>
<li class="chapter" data-level="9.9.2" data-path="multiple-regression.html"><a href="multiple-regression.html#sr2-in-practice"><i class="fa fa-check"></i><b>9.9.2</b> <span class="math inline">\(sr^2\)</span> in practice</a></li>
<li class="chapter" data-level="9.9.3" data-path="multiple-regression.html"><a href="multiple-regression.html#blocks-regression"><i class="fa fa-check"></i><b>9.9.3</b> Blocks regression</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="multiple-regression.html"><a href="multiple-regression.html#beta-weights"><i class="fa fa-check"></i><b>9.10</b> Beta-weights</a>
<ul>
<li class="chapter" data-level="9.10.1" data-path="multiple-regression.html"><a href="multiple-regression.html#in-practice"><i class="fa fa-check"></i><b>9.10.1</b> In practice</a></li>
<li class="chapter" data-level="9.10.2" data-path="multiple-regression.html"><a href="multiple-regression.html#old-school"><i class="fa fa-check"></i><b>9.10.2</b> Old school</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="multiple-regression.html"><a href="multiple-regression.html#graphing-2"><i class="fa fa-check"></i><b>9.11</b> Graphing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Welcome!</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-and-correlation" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Regression and correlation<a href="regression-and-correlation.html#regression-and-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The following CRAN packages must be installed:</p>
<table>
<thead>
<tr class="header">
<th>Required CRAN Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
</tr>
<tr class="even">
<td>apaTables</td>
</tr>
<tr class="odd">
<td>cocor</td>
</tr>
<tr class="even">
<td>janitor</td>
</tr>
<tr class="odd">
<td>psych</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th>Required Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="data_cor_sample_video_game.csv">data_cor_sample_video_game.csv</a></td>
</tr>
</tbody>
</table>
<div id="population-example" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Population example<a href="regression-and-correlation.html#population-example" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="ch_correlation/images/tetris.png" width="320" /></p>
<p>Consider the following the scenario, we want to examine the extent to which IQ predicts video game scores for people who live in the City of Guelph. We want to make conclusions about people who live in the City of Guelph so we refer to Guelph citizens as our population. Because we are interested in using IQ to predict video game score we refer to IQ as the <strong>predictor</strong>. The value being predicted is video game score and we refer to that variable as the <strong>criterion</strong> (i.e., the dependent variable). Imagine, for a moment, that we are actually able to get an IQ and a video game score for everyone in the City of Guelph (<em>N</em> = 100,000).</p>
<div id="no-predictor" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> No predictor<a href="regression-and-correlation.html#no-predictor" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We illustrate the range and variability of video game scores for everyone in the population below. There are 100,000 blue dots on this graph. Each blue dot represents a person in the <strong>population</strong>. The vertical position of the dot indicates each person’s video game.</p>
<ul>
<li><p>Notice the large number of dots (i.e., people) - there are so many that it’s hard to see individual dots/people.</p></li>
<li><p>The dots illustrate the range of video game scores - everyone did not obtain the same score.</p></li>
<li><p>We want to try to understand why, in this population, some people have higher vs lower video game scores.</p></li>
<li><p>Said another way, we want to explain, for this population, the variability in video game scores.</p></li>
<li><p>Correlation/regression can never provide evidence of causation (or explanation) but we can use those analyses to find a pattern in our data that is <em>consistent</em> with a causal relation. Then we conduct a second <strong>experimental</strong> study to determine if their really is a causal relation.</p></li>
</ul>
<p><img src="ch_correlation/images/pop_graph_arrow.png" width="70%" /></p>
<p>Without a predictor variable, our best estimate of a person’s video game score is the population mean. Moreover, without a predictor, we have the same estimate for everyone in the population - the mean video game score for the population. We have no way of creating an individualized estimate of someone’s video game score. The mean video game score is illustrated in the figure below with a horizontal green line.</p>
<p><img src="ch_correlation/images/pop_graph_mean.png" width="70%" /></p>
</div>
<div id="weak-relation" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Weak relation<a href="regression-and-correlation.html#weak-relation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can plot a variable (e.g., extraversion) against video game score to see if there is a relation between the two. In this case there doesn’t appear to be a relation. Indeed, this graph illustrates a zero correlation between extraversion and video game scores - the weakest possible relation for a predictor. Effectively, there is no linear relation between extraversion and video game scores.</p>
<p>As before, we place a horizontal green line on the graph to indicate the mean video game score. We also place a red regression line (i.e., best-fit line) on the graph; however, the red line is completely hidden by the green line representing the mean video game score. In this case, with these data, knowing a person’s extraversion score <strong>does not</strong> allow us to provide an individualized estimate of a person’s video game score. As a result, extraversion does not help us explain the variability in video game scores. That is, extraversion scores do not allow us to explain why some people have high video game score whereas other people have low video game scores.</p>
<p><img src="ch_correlation/images/pop_graph_extraversion_mean.png" width="70%" /></p>
</div>
<div id="strong-relation" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Strong relation<a href="regression-and-correlation.html#strong-relation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What if we were to try another variable – like IQ? The graph below illustrates a positive linear relation between IQ and video game score. As before, we place a green horizontal line on the graph to indicate the population mean. Additionally, we place a red regression line (i.e., a best-fit line) on the graph. This red regression line represents, for each person, an individualized estimate of video game score based on their IQ. The population-level regression line has the slope 8.00; which indicate that as IQ increase by 1.0 point video game score increases by 8.00 points. The equation for the regression line is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{score} &amp;= 8.00(IQ) + 200.31
\end{aligned}
\]</span></p>
<p>Or using the more generic X/Y notation:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{Y} &amp;= 8.00(X) + 200.31 \\
\end{aligned}
\]</span>
You can see in the graph below that, for some people, the individualized estimate of video game score (i.e., the y-axis position of the red line) is higher than the population mean. That is, in some cases the red regression is line is higher than the green line for the population mean. For other people, the individualized estimate of video game score (i.e., the y-axis position of the red line) is lower than the population mean. That is, in some cases the red regression is line is lower than the green line for the population mean. It appears that individuals with a high IQ tend to have a high video game score whereas individuals with a low IQ tend of have a low video game score. The regression line provides a more nuanced estimate for individual’s video game score than you can obtain by simply using the same estimation (i.e., the population mean) for everyone.</p>
<p><img src="ch_correlation/images/pop_graph_iq_line.png" width="70%" /></p>
<p>But how good is this model of the data? There are a variety of way of assessing model fit. We present two below. First, when you are only concerned about how well a single predictor performs, as is the case here, you can use a correlation. The symbol for the population correlation is <span class="math inline">\(\rho\)</span>. In these data, <span class="math inline">\(\rho = .60\)</span>. The correlation coefficient can range from -1 to 1. The further the correlation is from zero - the stronger the relation between the predictor and the criterion. That is, the further the correlation is from zero the better a linear model fits the data. A positive correlation indicates that as one variable increases the other variable also increases. A negative correlation indicates that as one variable increases the other variable decreases.</p>
<p>Cohen’s benchmarks are below:</p>
<table>
<thead>
<tr class="header">
<th align="center">Cohen (1988) Label</th>
<th align="center">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Small</td>
<td align="center"><span class="math inline">\(\rho\)</span> = .10</td>
</tr>
<tr class="even">
<td align="center">Medium</td>
<td align="center"><span class="math inline">\(\rho\)</span> = .30</td>
</tr>
<tr class="odd">
<td align="center">Large</td>
<td align="center"><span class="math inline">\(\rho\)</span> = .50</td>
</tr>
</tbody>
</table>
<p>An alternative, and more general, means of assessing the quality of statistical model is to use <span class="math inline">\(R^2\)</span>. This indexes the proportion of video game scores that are accounted for by a statistical model. One important attribute of <span class="math inline">\(R^2\)</span> is that can be used when there are multiple predictors. When there is only one predictor, <span class="math inline">\(R^2\)</span> is simply the correlation squared. Thus, at the population level, <strong>when there is only one predictor</strong>:</p>
<p><span class="math display">\[
\begin{aligned}
R^2  = \rho^2
\end{aligned}
\]</span></p>
<p>To summarize, the population-level values (i.e., parameters):</p>
<ul>
<li><p>Slope = 8.00</p></li>
<li><p><span class="math inline">\(\rho = .60\)</span></p></li>
<li><p><span class="math inline">\(R^2 = .36\)</span></p></li>
</ul>
<p>In the next section we use sample-level data to estimate these population-level values.</p>
</div>
</div>
<div id="consider-a-sample" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Consider a sample<a href="regression-and-correlation.html#consider-a-sample" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Unfortunately, we never/rarely have data for everyone in the population (in this example everyone in the City of Guelph). Consequently, we usually have to select a subset of the population as a sample and use sample data for our analyses. In the figure below there are 100,000 blue dots - each dot represents an individual in the population. Additionally, there are also 9 black dots. These black dots are a random subset of the population – our sample. We will use the data from our sample (i.e., the 9 black dots) to estimate the slope, correlation, and <span class="math inline">\(R^2\)</span> for the population (i.e., the 100,000 blue dots).</p>
<p><img src="ch_correlation/images/pop_sample_graph.png" width="70%" /></p>
<p>We always need to remember the values calculated from our sample (statistics) are only estimates of the population-level parameters; estimates that are likely are likely to differ from population parameters due to sampling error.</p>
<p>Let’s look at our sample in more detail. Notice, in the figure below, that there is one data point (<span class="math inline">\(X_i\)</span>, <span class="math inline">\(Y_i\)</span>) for each of the 9 people. We illustrate the mean video game score for the 9 people with the horizontal green line.</p>
<p><img src="ch_correlation/images/sample_plot1.png" width="80%" /></p>
<p>We can calculate the variance of the video game scores using the formula below.</p>
<p><span class="math display">\[
\begin{aligned}
s^2_{score} = \frac{\sum{(Y_i - \bar{Y})^2}}{N-1}
\end{aligned}
\]</span></p>
<p>It’s often useful to just focus on the numerator of this equation. We call this Sum of Squares Total (SSR):</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Total} = \sum{(Y_i - \bar{Y})^2}
\end{aligned}
\]</span></p>
<p>The values used in the <strong>Sum of Squares Total</strong> calculation are illustrated in the figure below. The vertical blue line indicates the difference between <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(\bar{Y}\)</span>. The <span class="math inline">\(SS_{Total}\)</span> value indexes the variability of the <strong>actual</strong> video game scores around the sample mean.</p>
<p><img src="ch_correlation/images/sample_plot2.png" width="80%" /></p>
<p>In the figure below we add the regression line in red. The regression line is a statistical model for the data (a best-fit line). The regression line will always run through the joint mean of the two variables (i.e., the [<span class="math inline">\(\bar{X}\)</span>, <span class="math inline">\(\bar{Y}\)</span>] point).</p>
<p><img src="ch_correlation/images/sample_plot3.png" width="80%" /></p>
<p>Recall that the regression line represents an individualized estimate of each person’s video game score derived from their IQ (via the regression equation). Later we will show you how to calculate the regression line. For now, accept that the regression equation for the sample in standard notation is:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{Y_i} &amp;= 9.44(X_i) -21.21 \\
\end{aligned}
\]</span></p>
<p>And contextualized to the variable names is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{score_i} &amp;= 9.44(IQ_i) -21.21
\end{aligned}
\]</span></p>
<p>Therefore, the predicted value for Jane is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{score_i} &amp;= 9.44(IQ_i) -21.21 \\
&amp;= 9.44(71) - 21.21 \\
&amp;= 649 \text{(rounded)} \\
\end{aligned}
\]</span></p>
<p>You can see this calculation for everyone in the sample:</p>
<p><img src="ch_correlation/images/yhat_data.png" width="490" /></p>
<p>In the graph below each person is represented by a blue dot. The estimate of each person’s video game score, <span class="math inline">\(\hat{Y_i}\)</span>, derived from the regression equation, is indicated by a red dot on the red regression line. The vertical blue lines are used to indicate, for each person (i.e., blue dot, <span class="math inline">\(Y_i\)</span>), the estimate of their video game score (i.e., red dot, <span class="math inline">\(\hat{Y_i}\)</span>).</p>
<p><img src="ch_correlation/images/sample_plot4.png" width="80%" /></p>
<p>We can calculate the extent to which individualized estimates are better than the sample mean for modeling the data. That is, we can calculate the extent to which the regression line is better at modeling the data than the mean line. We do so by calculating the extent to which the individualized estimates on the regression line differ from the sample mean. This is done with the calculation below for the <strong>Sum of Squares Regression</strong>.</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Regression} = \sum{(\hat{Y_i} - \bar{Y})^2}
\end{aligned}
\]</span></p>
<p>The values used in the <strong>Sum of Squares Regression</strong> calculation are illustrated in the figure below. The vertical red line indicates the difference between <span class="math inline">\(\hat{Y_i}\)</span> and <span class="math inline">\(\bar{Y}\)</span>. The <span class="math inline">\(SS_{Regression}\)</span> value indexes the variability of the <strong>estimates</strong> of video game scores around the sample mean. The longer the vertical red line (i.e., the larger the <span class="math inline">\((\hat{Y_i} - \bar{Y})\)</span> difference) the better the model. Longer vertical red lines are associated with models that do a better job of accounting for variability in video scores.</p>
<p><img src="ch_correlation/images/sample_plot5.png" width="80%" /></p>
<p>So far we have calculated two values, <span class="math inline">\(SS_{Regression}\)</span> and <span class="math inline">\(SS_{Total}\)</span>. The <span class="math inline">\(SS_{Total}\)</span> value indexes the variability of <strong>actual</strong> video game scores about the sample mean (it’s the numerator for the variance calculation). In contrast, <span class="math inline">\(SS_{Regression}\)</span> indexes the variability of <strong>estimated</strong> video game scores about the sample mean. We can calculate the proportion of the variability in actual scores accounted for the statistical model (i.e., regression line) using <span class="math inline">\(R^2\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
R^2 = \frac{SS_{Regression}}{SS_{Total}}
\end{aligned}
\]</span>
We can also think of this as in terms of variance (because N-1 terms cancel each other out).</p>
<p><span class="math display">\[
\begin{aligned}
R^2 &amp;= \frac{\text{Variance of predicted scores}}{\text{Variance of actual scores}} \\
&amp;= \frac{\frac{\sum{(\hat{Y_i} - \bar{Y})^2}}{N-1}}{\frac{\sum{(Y_i - \bar{Y})^2}}{N-1}} \\
&amp;= \frac{\sum{(\hat{Y_i} - \bar{Y})^2}}{\sum{(Y_i - \bar{Y})^2}} \\
&amp;= \frac{SS_{Regression}}{SS_{Total}}\\
\end{aligned}
\]</span></p>
<div id="regression" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> Regression<a href="regression-and-correlation.html#regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s obtain the actual value for <span class="math inline">\(R^2\)</span>, as well as the slope, using R. We can obtain the regression model (i.e.. linear model or lm) using the command below:</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="regression-and-correlation.html#cb310-1" tabindex="-1"></a>lm_object <span class="ot">&lt;-</span> <span class="fu">lm</span>(video_game <span class="sc">~</span> iq,</span>
<span id="cb310-2"><a href="regression-and-correlation.html#cb310-2" tabindex="-1"></a>                <span class="at">data =</span> sample_data)</span></code></pre></div>
<p>We display the result using apaTables:</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="regression-and-correlation.html#cb311-1" tabindex="-1"></a><span class="fu">library</span>(apaTables)</span>
<span id="cb311-2"><a href="regression-and-correlation.html#cb311-2" tabindex="-1"></a></span>
<span id="cb311-3"><a href="regression-and-correlation.html#cb311-3" tabindex="-1"></a><span class="fu">apa.reg.table</span>(lm_object,</span>
<span id="cb311-4"><a href="regression-and-correlation.html#cb311-4" tabindex="-1"></a>              <span class="at">table.number =</span> <span class="dv">1</span>,</span>
<span id="cb311-5"><a href="regression-and-correlation.html#cb311-5" tabindex="-1"></a>              <span class="at">filename =</span> <span class="st">&quot;regression_table.doc&quot;</span>)</span></code></pre></div>
<p>Which produces the output:</p>
<p><img src="ch_correlation/images/regression_output.png" width="1018" /></p>
<p>If we examine the fit column on the far right of the output above we see <span class="math inline">\(R^2\)</span> = .74, 95% CI [.17, .86]. This value indicates that in this sample 74% of the variability in video scores is accounted accounted for by the statistical model (i.e., red regression line). The confidence interval suggests a plausible range of values for the <span class="math inline">\(R^2\)</span> at the population-level is .17 to .86. Notice that this range captures that population-level <span class="math inline">\(R^2\)</span> of .36 that we calculated from the entire population previously.</p>
<p><span class="math display">\[
\begin{aligned}
R^2 &amp;= .736 = .74\\\\
\end{aligned}
\]</span></p>
<p>If we examine the b column in the output we can create the regression equations below:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{Y_i} &amp;= 9.44(X_i) -21.21 \\
\widehat{score_i} &amp;= 9.44(IQ_i) -21.21\\
\end{aligned}
\]</span></p>
<p>This tells use the slope in our sample is 9.44, 95% CI [4.39, 14.50]. That is, in the sample, each IQ point is associated with an additional 9.44 points in the video game. The population regression line might have a smaller/larger slope. The 95% confidence intervals tells us that a plausible range of values for the slope of the regression line at the population-level is 4.39 to 14.50. Notice that this range captures that population-level slope of 8.00 that we calculated from the entire population previously.</p>
<p>Additional regression details are provided with the command below.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="regression-and-correlation.html#cb312-1" tabindex="-1"></a><span class="fu">summary</span>(lm_object)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = video_game ~ iq, data = sample_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -201.2  -80.4   58.6   79.8  151.3 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)   -21.21     225.86   -0.09   0.9278   
## iq              9.44       2.14    4.42   0.0031 **
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 130 on 7 degrees of freedom
## Multiple R-squared:  0.736,  Adjusted R-squared:  0.698 
## F-statistic: 19.5 on 1 and 7 DF,  p-value: 0.00309</code></pre>
</div>
<div id="correlation" class="section level3 hasAnchor" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> Correlation<a href="regression-and-correlation.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As discussed previously, a correlation can be considered a fit index for a linear regression line. That is, a correlation indicates the extent to which the data fit a straight line (i.e., the extent to which the data fit a linear model). Correlation values range between -1 and +1. The further a correlation value is from 0 the more tightly points will cluster around the regression line.</p>
<ul>
<li><p>A <strong>positive correlation</strong> indicates that as one value <strong>increases</strong> the other value <strong>increases</strong>. For example, as height increases weight increases.</p></li>
<li><p>A <strong>negative correlation</strong> indicates that as one value <strong>increases</strong> the other values <strong>decreases</strong>. For example, as study time increases the number of errors on an exam decreases.</p></li>
</ul>
<p>A few possible <strong>positive</strong> correlations are illustrated below – notice the relation between the graph and the strength of the correlation.</p>
<p><img src="ch_correlation/images/cor_mag.png" width="80%" height="80%" /></p>
<p>You can obtain the correlation from our sample data with the command below:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="regression-and-correlation.html#cb314-1" tabindex="-1"></a><span class="fu">cor.test</span>(sample_data<span class="sc">$</span>iq, sample_data<span class="sc">$</span>video_game, </span>
<span id="cb314-2"><a href="regression-and-correlation.html#cb314-2" tabindex="-1"></a>         <span class="at">na.action =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sample_data$iq and sample_data$video_game
## t = 4.4, df = 7, p-value = 0.003
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4503 0.9696
## sample estimates:
##    cor 
## 0.8579</code></pre>
<p>From this output we extract the numbers below in APA reporting style:</p>
<p>There was a positive relation between IQ and video game score, such that as IQ increased, so did video game score, <span class="math inline">\(r\)</span> = .86, 95% CI[.45, .97], <span class="math inline">\(p\)</span> = .003, <em>N</em> = 9.</p>
</div>
<div id="graphing-1" class="section level3 hasAnchor" number="8.2.3">
<h3><span class="header-section-number">8.2.3</span> Graphing<a href="regression-and-correlation.html#graphing-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A scatter plot can be made code below:</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="regression-and-correlation.html#cb316-1" tabindex="-1"></a>my_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> sample_data, </span>
<span id="cb316-2"><a href="regression-and-correlation.html#cb316-2" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> iq, <span class="at">y =</span> video_game)) <span class="sc">+</span> </span>
<span id="cb316-3"><a href="regression-and-correlation.html#cb316-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb316-4"><a href="regression-and-correlation.html#cb316-4" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">140</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">400</span>, <span class="dv">1500</span>)) <span class="sc">+</span></span>
<span id="cb316-5"><a href="regression-and-correlation.html#cb316-5" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">400</span>, <span class="dv">1500</span>, <span class="at">by =</span> <span class="dv">200</span>)) <span class="sc">+</span> </span>
<span id="cb316-6"><a href="regression-and-correlation.html#cb316-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">70</span>, <span class="dv">140</span>, <span class="at">by =</span> <span class="dv">20</span>)) <span class="sc">+</span></span>
<span id="cb316-7"><a href="regression-and-correlation.html#cb316-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;IQ&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Video Game Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb316-8"><a href="regression-and-correlation.html#cb316-8" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="dv">24</span>)</span></code></pre></div>
</div>
</div>
<div id="comparing-correlations" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Comparing correlations<a href="regression-and-correlation.html#comparing-correlations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this part of the chapter we compare correlations within and across studies we do so with the cocor package. We begin by obtaining a data set from the psych package. Note that we <strong>do not</strong> use the library(psych) command due to conflicts with the tidyverse.</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="regression-and-correlation.html#cb317-1" tabindex="-1"></a><span class="co"># Obtain the bfi data set from the psych package</span></span>
<span id="cb317-2"><a href="regression-and-correlation.html#cb317-2" tabindex="-1"></a>bfi <span class="ot">&lt;-</span> psych<span class="sc">::</span>bfi</span>
<span id="cb317-3"><a href="regression-and-correlation.html#cb317-3" tabindex="-1"></a></span>
<span id="cb317-4"><a href="regression-and-correlation.html#cb317-4" tabindex="-1"></a><span class="co"># remove empty rows/columns and clean the variable names</span></span>
<span id="cb317-5"><a href="regression-and-correlation.html#cb317-5" tabindex="-1"></a>bfi <span class="ot">&lt;-</span> bfi <span class="sc">%&gt;%</span></span>
<span id="cb317-6"><a href="regression-and-correlation.html#cb317-6" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">&quot;rows&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb317-7"><a href="regression-and-correlation.html#cb317-7" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">&quot;cols&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb317-8"><a href="regression-and-correlation.html#cb317-8" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code></pre></div>
<p>Check out the large number of columns.</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="regression-and-correlation.html#cb318-1" tabindex="-1"></a><span class="fu">glimpse</span>(bfi)</span></code></pre></div>
<pre><code>## Rows: 2,800
## Columns: 28
## $ a1        &lt;int&gt; 2, 2, 5, 4, 2, 6, 2, 4, 4, 2, 4, 2, 5, 5…
## $ a2        &lt;int&gt; 4, 4, 4, 4, 3, 6, 5, 3, 3, 5, 4, 5, 5, 5…
## $ a3        &lt;int&gt; 3, 5, 5, 6, 3, 5, 5, 1, 6, 6, 5, 5, 5, 5…
## $ a4        &lt;int&gt; 4, 2, 4, 5, 4, 6, 3, 5, 3, 6, 6, 5, 6, 6…
## $ a5        &lt;int&gt; 4, 5, 4, 5, 5, 5, 5, 1, 3, 5, 5, 5, 4, 6…
## $ c1        &lt;int&gt; 2, 5, 4, 4, 4, 6, 5, 3, 6, 6, 4, 5, 5, 4…
## $ c2        &lt;int&gt; 3, 4, 5, 4, 4, 6, 4, 2, 6, 5, 3, 4, 4, 4…
## $ c3        &lt;int&gt; 3, 4, 4, 3, 5, 6, 4, 4, 3, 6, 5, 5, 3, 4…
## $ c4        &lt;int&gt; 4, 3, 2, 5, 3, 1, 2, 2, 4, 2, 3, 4, 2, 2…
## $ c5        &lt;int&gt; 4, 4, 5, 5, 2, 3, 3, 4, 5, 1, 2, 5, 2, 1…
## $ e1        &lt;int&gt; 3, 1, 2, 5, 2, 2, 4, 3, 5, 2, 1, 3, 3, 2…
## $ e2        &lt;int&gt; 3, 1, 4, 3, 2, 1, 3, 6, 3, 2, 3, 3, 3, 2…
## $ e3        &lt;int&gt; 3, 6, 4, 4, 5, 6, 4, 4, NA, 4, 2, 4, 3, …
## $ e4        &lt;int&gt; 4, 4, 4, 4, 4, 5, 5, 2, 4, 5, 5, 5, 2, 6…
## $ e5        &lt;int&gt; 4, 3, 5, 4, 5, 6, 5, 1, 3, 5, 4, 4, 4, 5…
## $ n1        &lt;int&gt; 3, 3, 4, 2, 2, 3, 1, 6, 5, 5, 3, 4, 1, 1…
## $ n2        &lt;int&gt; 4, 3, 5, 5, 3, 5, 2, 3, 5, 5, 3, 5, 2, 1…
## $ n3        &lt;int&gt; 2, 3, 4, 2, 4, 2, 2, 2, 2, 5, 4, 3, 2, 1…
## $ n4        &lt;int&gt; 2, 5, 2, 4, 4, 2, 1, 6, 3, 2, 2, 2, 2, 2…
## $ n5        &lt;int&gt; 3, 5, 3, 1, 3, 3, 1, 4, 3, 4, 3, NA, 2, …
## $ o1        &lt;int&gt; 3, 4, 4, 3, 3, 4, 5, 3, 6, 5, 5, 4, 4, 5…
## $ o2        &lt;int&gt; 6, 2, 2, 3, 3, 3, 2, 2, 6, 1, 3, 6, 2, 3…
## $ o3        &lt;int&gt; 3, 4, 5, 4, 4, 5, 5, 4, 6, 5, 5, 4, 4, 4…
## $ o4        &lt;int&gt; 4, 3, 5, 3, 3, 6, 6, 5, 6, 5, 6, 5, 5, 4…
## $ o5        &lt;int&gt; 3, 3, 2, 5, 3, 1, 1, 3, 1, 2, 3, 4, 2, 4…
## $ gender    &lt;int&gt; 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1…
## $ education &lt;int&gt; NA, NA, NA, NA, NA, 3, NA, 2, 1, NA, 1, …
## $ age       &lt;int&gt; 16, 18, 17, 17, 17, 21, 18, 19, 19, 17, …</code></pre>
<p>Let’s select a small subset of the columns for our example:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="regression-and-correlation.html#cb320-1" tabindex="-1"></a>bfi <span class="ot">&lt;-</span> bfi <span class="sc">%&gt;%</span></span>
<span id="cb320-2"><a href="regression-and-correlation.html#cb320-2" tabindex="-1"></a>  <span class="fu">select</span>(a1, c1, e1, o1, gender)</span></code></pre></div>
<p>You can confirm the smaller set of columns:</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="regression-and-correlation.html#cb321-1" tabindex="-1"></a><span class="fu">glimpse</span>(bfi)</span></code></pre></div>
<pre><code>## Rows: 2,800
## Columns: 5
## $ a1     &lt;int&gt; 2, 2, 5, 4, 2, 6, 2, 4, 4, 2, 4, 2, 5, 5, 4…
## $ c1     &lt;int&gt; 2, 5, 4, 4, 4, 6, 5, 3, 6, 6, 4, 5, 5, 4, 5…
## $ e1     &lt;int&gt; 3, 1, 2, 5, 2, 2, 4, 3, 5, 2, 1, 3, 3, 2, 3…
## $ o1     &lt;int&gt; 3, 4, 4, 3, 3, 4, 5, 3, 6, 5, 5, 4, 4, 5, 5…
## $ gender &lt;int&gt; 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1…</code></pre>
<p>These columns are single items from a personality measure.</p>
<ul>
<li><p>a1 (Agreeableness)</p></li>
<li><p>c1 (Conscientiousness)</p></li>
<li><p>e1 (Extraversion)</p></li>
<li><p>o1 (Opennness)</p></li>
</ul>
<p>You can obtain a condensed correlation matrix using the cor() command. You can specify use = “pairwise.complete.obs” for pairwise correlation - the documentation covers other options. The round(2) command rounds the correlations to two decimal places.</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="regression-and-correlation.html#cb323-1" tabindex="-1"></a><span class="fu">cor</span>(bfi, <span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb323-2"><a href="regression-and-correlation.html#cb323-2" tabindex="-1"></a>    <span class="fu">round</span>(<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##           a1    c1    e1    o1 gender
## a1      1.00  0.03  0.11  0.01  -0.16
## c1      0.03  1.00 -0.02  0.17   0.01
## e1      0.11 -0.02  1.00 -0.10  -0.13
## o1      0.01  0.17 -0.10  1.00  -0.10
## gender -0.16  0.01 -0.13 -0.10   1.00</code></pre>
<p>Or we could use apaTable apa.cor.table() command:</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="regression-and-correlation.html#cb325-1" tabindex="-1"></a><span class="fu">library</span>(apaTables)</span>
<span id="cb325-2"><a href="regression-and-correlation.html#cb325-2" tabindex="-1"></a></span>
<span id="cb325-3"><a href="regression-and-correlation.html#cb325-3" tabindex="-1"></a><span class="fu">apa.cor.table</span>(bfi,</span>
<span id="cb325-4"><a href="regression-and-correlation.html#cb325-4" tabindex="-1"></a>              <span class="at">table.number =</span> <span class="dv">1</span>,</span>
<span id="cb325-5"><a href="regression-and-correlation.html#cb325-5" tabindex="-1"></a>              <span class="at">filename =</span> <span class="st">&quot;table_1_bfi.doc&quot;</span>)</span></code></pre></div>
<p><img src="ch_correlation/images/table1_bfi.png" width="80%" /></p>
<p>Inspecting the above table you see that the correlation between a1 and c1 with is <em>r</em> = .03, 95% CI [-.01, .07]. Likewise, the correlation between e1 and o1 is <em>r</em> = -.10, 95% CI [-.14, -.06]. We obtain the <em>p</em>-values for these relations below.</p>
<div id="p-values" class="section level3 hasAnchor" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> p-values<a href="regression-and-correlation.html#p-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The code below obtains the <em>p</em>-value for the a1/c1 relation - a value of .144.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="regression-and-correlation.html#cb326-1" tabindex="-1"></a><span class="fu">cor.test</span>(bfi<span class="sc">$</span>a1, bfi<span class="sc">$</span>c1)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  bfi$a1 and bfi$c1
## t = 1.5, df = 2762, p-value = 0.1
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.00949  0.06502
## sample estimates:
##    cor 
## 0.0278</code></pre>
<p>The code below obtains the <em>p</em>-value for the e1/o1 relation - a value sufficiently small we report it as <span class="math inline">\(p\)</span> &lt; .001</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="regression-and-correlation.html#cb328-1" tabindex="-1"></a><span class="fu">cor.test</span>(bfi<span class="sc">$</span>e1, bfi<span class="sc">$</span>o1)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  bfi$e1 and bfi$o1
## t = -5.3, df = 2757, p-value = 1e-07
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.13718 -0.06329
## sample estimates:
##     cor 
## -0.1004</code></pre>
<p>With <em>p</em>-values in hand we can write this up as:</p>
<p>Inspecting the above table you see that the correlation between a1 and c1 with is <em>r</em> = .03, 95% CI [-.01, .07], <em>p</em> = .144. Likewise, the correlation between e1 and o1 is <em>r</em> = -.10, 95% CI [-.14, -.06], <em>p</em> &lt; .001.</p>
</div>
<div id="within-a-data-set" class="section level3 hasAnchor" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> Within a data set<a href="regression-and-correlation.html#within-a-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this section we look at comparing correlation within a single data set.</p>
<div id="non-overlapping-correlations" class="section level4 hasAnchor" number="8.3.2.1">
<h4><span class="header-section-number">8.3.2.1</span> Non-overlapping correlations<a href="regression-and-correlation.html#non-overlapping-correlations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We will compare the correlation to between (a1, c1) to the correlation between (e1, o1) with the cocor package. In this case, because neither of the variables in the first correlation (a1, c1) are in the second correlation (e1, o1) we refer to this as a non-overlapping correlation comparison.</p>
<p>The cocor command will provide a lot of output. We are most interested in the last part of the output corresponding to Zou (2007) which provides the confidence interval for the difference in the correlations. But we also want to examine the first part of the output which will show us the two original correlations (a1, c1) = 0.0276, and (e1, o1) = -0.1002 (these are the .03 and -.10 values prior to rounding). As well it also shows us the difference between them, Difference: r.jk - r.hm = 0.1278.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="regression-and-correlation.html#cb330-1" tabindex="-1"></a><span class="fu">library</span>(cocor)</span>
<span id="cb330-2"><a href="regression-and-correlation.html#cb330-2" tabindex="-1"></a></span>
<span id="cb330-3"><a href="regression-and-correlation.html#cb330-3" tabindex="-1"></a><span class="fu">cocor</span>( <span class="sc">~</span> a1 <span class="sc">+</span> c1 <span class="sc">|</span> e1 <span class="sc">+</span> o1, <span class="at">data =</span> <span class="fu">as.data.frame</span>(bfi))</span></code></pre></div>
<pre><code>## 
##   Results of a comparison of two nonoverlapping correlations based on dependent groups
## 
## Comparison between r.jk (a1, c1) = 0.0276 and r.hm (e1, o1) = -0.1002
## Difference: r.jk - r.hm = 0.1278
## Related correlations: r.jh = 0.1036, r.jm = 0.0125, r.kh = -0.0259, r.km = 0.1688
## Data: as.data.frame(bfi): j = a1, k = c1, h = e1, m = o1
## Group size: n = 2724
## Null hypothesis: r.jk is equal to r.hm
## Alternative hypothesis: r.jk is not equal to r.hm (two-sided)
## Alpha: 0.05
## 
## pearson1898: Pearson and Filon&#39;s z (1898)
##   z = 4.7832, p-value = 0.0000
##   Null hypothesis rejected
## 
## dunn1969: Dunn and Clark&#39;s z (1969)
##   z = 4.7676, p-value = 0.0000
##   Null hypothesis rejected
## 
## steiger1980: Steiger&#39;s (1980) modification of Dunn and Clark&#39;s z (1969) using average correlations
##   z = 4.7671, p-value = 0.0000
##   Null hypothesis rejected
## 
## raghunathan1996: Raghunathan, Rosenthal, and Rubin&#39;s (1996) modification of Pearson and Filon&#39;s z (1898)
##   z = 4.7676, p-value = 0.0000
##   Null hypothesis rejected
## 
## silver2004: Silver, Hittner, and May&#39;s (2004) modification of Dunn and Clark&#39;s z (1969) using a backtransformed average Fisher&#39;s (1921) Z procedure
##   z = 4.7671, p-value = 0.0000
##   Null hypothesis rejected
## 
## zou2007: Zou&#39;s (2007) confidence interval
##   95% confidence interval for r.jk - r.hm: 0.0753 0.1800
##   Null hypothesis rejected (Interval does not include 0)</code></pre>
<p>We could write this as:</p>
<p>There was a negative weak relation between extraversion (e1) and openness (o1) such that as extraversion increased openness decreased, <em>r</em> = -.10, 95% CI [-.14, -.06], <em>p</em> &lt; .001. In contrast, the relation between agreeableness (a1) and conscientiousness(c1) was non-significant, <em>r</em> = .03, 95% CI [-.01, .07], <em>p</em> = .144. The extraversion/openness relation was stronger than the agreeableness/conscientiousness relation, <span class="math inline">\(\Delta\)</span><em>r</em> = .13, 95% CI [.07, .18], <em>p</em> &lt; .001.</p>
</div>
<div id="overlapping-correlations" class="section level4 hasAnchor" number="8.3.2.2">
<h4><span class="header-section-number">8.3.2.2</span> Overlapping correlations<a href="regression-and-correlation.html#overlapping-correlations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We will compare the correlation to between (a1, c1) to the correlation between (a1, e1) with cocor. In this case, because a1 is common to the first correlation (a1, c1) and the second correlation (e1, o1) we refer to this as an overlapping correlation comparison.</p>
<p>We obtain the (a1, e1) correlation, below, and find: <em>r</em> = .11, 95% [.07, .14], <em>p</em> &lt; .001.</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="regression-and-correlation.html#cb332-1" tabindex="-1"></a><span class="fu">cor.test</span>(bfi<span class="sc">$</span>a1, bfi<span class="sc">$</span>e1)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  bfi$a1 and bfi$e1
## t = 5.6, df = 2759, p-value = 2e-08
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.06917 0.14294
## sample estimates:
##    cor 
## 0.1062</code></pre>
<p>We obtain the (a1, c1) correlation, below, and find: <em>r</em> = .03, 95% [-.00, .07], <em>p</em> = .14.</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="regression-and-correlation.html#cb334-1" tabindex="-1"></a><span class="fu">cor.test</span>(bfi<span class="sc">$</span>a1, bfi<span class="sc">$</span>c1)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  bfi$a1 and bfi$c1
## t = 1.5, df = 2762, p-value = 0.1
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.00949  0.06502
## sample estimates:
##    cor 
## 0.0278</code></pre>
<p>We use the cocor command to compare the two relations:</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="regression-and-correlation.html#cb336-1" tabindex="-1"></a><span class="fu">library</span>(cocor)</span>
<span id="cb336-2"><a href="regression-and-correlation.html#cb336-2" tabindex="-1"></a></span>
<span id="cb336-3"><a href="regression-and-correlation.html#cb336-3" tabindex="-1"></a><span class="fu">cocor</span>( <span class="sc">~</span> a1 <span class="sc">+</span> c1 <span class="sc">|</span> a1 <span class="sc">+</span> e1, <span class="at">data =</span> <span class="fu">as.data.frame</span>(bfi))</span></code></pre></div>
<pre><code>## 
##   Results of a comparison of two overlapping correlations based on dependent groups
## 
## Comparison between r.jk (a1, c1) = 0.0263 and r.jh (a1, e1) = 0.1047
## Difference: r.jk - r.jh = -0.0784
## Related correlation: r.kh = -0.0248
## Data: as.data.frame(bfi): j = a1, k = c1, h = e1
## Group size: n = 2741
## Null hypothesis: r.jk is equal to r.jh
## Alternative hypothesis: r.jk is not equal to r.jh (two-sided)
## Alpha: 0.05
## 
## pearson1898: Pearson and Filon&#39;s z (1898)
##   z = -2.8820, p-value = 0.0040
##   Null hypothesis rejected
## 
## hotelling1940: Hotelling&#39;s t (1940)
##   t = -2.8827, df = 2738, p-value = 0.0040
##   Null hypothesis rejected
## 
## williams1959: Williams&#39; t (1959)
##   t = -2.8793, df = 2738, p-value = 0.0040
##   Null hypothesis rejected
## 
## olkin1967: Olkin&#39;s z (1967)
##   z = -2.8820, p-value = 0.0040
##   Null hypothesis rejected
## 
## dunn1969: Dunn and Clark&#39;s z (1969)
##   z = -2.8775, p-value = 0.0040
##   Null hypothesis rejected
## 
## hendrickson1970: Hendrickson, Stanley, and Hills&#39; (1970) modification of Williams&#39; t (1959)
##   t = -2.8827, df = 2738, p-value = 0.0040
##   Null hypothesis rejected
## 
## steiger1980: Steiger&#39;s (1980) modification of Dunn and Clark&#39;s z (1969) using average correlations
##   z = -2.8765, p-value = 0.0040
##   Null hypothesis rejected
## 
## meng1992: Meng, Rosenthal, and Rubin&#39;s z (1992)
##   z = -2.8754, p-value = 0.0040
##   Null hypothesis rejected
##   95% confidence interval for r.jk - r.jh: -0.1325 -0.0251
##   Null hypothesis rejected (Interval does not include 0)
## 
## hittner2003: Hittner, May, and Silver&#39;s (2003) modification of Dunn and Clark&#39;s z (1969) using a backtransformed average Fisher&#39;s (1921) Z procedure
##   z = -2.8765, p-value = 0.0040
##   Null hypothesis rejected
## 
## zou2007: Zou&#39;s (2007) confidence interval
##   95% confidence interval for r.jk - r.jh: -0.1317 -0.0250
##   Null hypothesis rejected (Interval does not include 0)</code></pre>
<p>The cocor command provides a lot of output. We are most interested in the last part of the output corresponding to Zou (2007) which provides the confidence interval for the difference: -.13 to -.03. But we also want to examine the first part of the output which will show us the two original correlations <span class="math inline">\(r_{(a1, c1)}\)</span> = 0.0276, and <span class="math inline">\(r_{(a1, e1)}\)</span> = 0.10472 As well, the output also shows us the difference between thesee two correlations, Difference: r.jk - r.jh = -0.0784 (with rounding, -.08).</p>
<p>We can write this up as:</p>
<p>Agreeableness and extraversion were weakly related, <em>r</em> = .11, 95% [.07, .14], <em>p</em> &lt; .001, such that as agreeableness increased so did extraversion. The relation between agreeableness and conscientiousness was non-significant, <em>r</em> = .03, 95% [-.00, .07], <em>p</em> = .14. The agreeableness/extraversion relation was significantly stronger than the agreeableness/conscientiousness relation, <span class="math inline">\(\Delta\)</span><em>r</em> = .08, 95% CI [.03, .13], <em>p</em> = .004.</p>
</div>
</div>
<div id="between-data-sets" class="section level3 hasAnchor" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> Between data sets<a href="regression-and-correlation.html#between-data-sets" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this section we look at comparing correlations from two data sets.</p>
<div id="create-seperate-data-files-for-men-and-women-if-needed" class="section level4 hasAnchor" number="8.3.3.1">
<h4><span class="header-section-number">8.3.3.1</span> Create seperate data files for men and women (if needed)<a href="regression-and-correlation.html#create-seperate-data-files-for-men-and-women-if-needed" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We begin by creating two separate data sets - one for men and one for women:</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="regression-and-correlation.html#cb338-1" tabindex="-1"></a>bfi_men   <span class="ot">&lt;-</span> bfi <span class="sc">%&gt;%</span></span>
<span id="cb338-2"><a href="regression-and-correlation.html#cb338-2" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb338-3"><a href="regression-and-correlation.html#cb338-3" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>gender)</span>
<span id="cb338-4"><a href="regression-and-correlation.html#cb338-4" tabindex="-1"></a></span>
<span id="cb338-5"><a href="regression-and-correlation.html#cb338-5" tabindex="-1"></a>bfi_women <span class="ot">&lt;-</span> bfi <span class="sc">%&gt;%</span></span>
<span id="cb338-6"><a href="regression-and-correlation.html#cb338-6" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb338-7"><a href="regression-and-correlation.html#cb338-7" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>gender)</span></code></pre></div>
<p>Use glimpse() to check out the subgroups. Note that it also tells you the number of participants in each subgroup.</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="regression-and-correlation.html#cb339-1" tabindex="-1"></a><span class="fu">glimpse</span>(bfi_men)</span></code></pre></div>
<pre><code>## Rows: 919
## Columns: 4
## $ a1 &lt;int&gt; 2, 2, 2, 4, 4, 4, 2, 5, 4, 4, 5, 5, 1, 4, 1, 4,…
## $ c1 &lt;int&gt; 2, 4, 5, 3, 6, 4, 5, 4, 5, 5, 5, 4, 4, 5, 1, 4,…
## $ e1 &lt;int&gt; 3, 2, 4, 3, 5, 1, 3, 2, 3, 1, 2, 3, 2, 3, 6, 2,…
## $ o1 &lt;int&gt; 3, 3, 5, 3, 6, 5, 4, 5, 5, 6, 5, 6, 6, 6, 6, 4,…</code></pre>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="regression-and-correlation.html#cb341-1" tabindex="-1"></a><span class="fu">glimpse</span>(bfi_women)</span></code></pre></div>
<pre><code>## Rows: 1,881
## Columns: 4
## $ a1 &lt;int&gt; 2, 5, 4, 6, 2, 5, 4, 4, 4, 1, 2, 1, 2, 2, 2, 4,…
## $ c1 &lt;int&gt; 5, 4, 4, 6, 6, 5, 4, 5, 1, 5, 3, 5, 6, 4, 5, 5,…
## $ e1 &lt;int&gt; 1, 2, 5, 2, 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1,…
## $ o1 &lt;int&gt; 4, 4, 3, 4, 5, 4, 5, 4, 4, 5, 6, 6, 5, 6, 2, 4,…</code></pre>
</div>
<div id="check-out-the-subgroup-correlations" class="section level4 hasAnchor" number="8.3.3.2">
<h4><span class="header-section-number">8.3.3.2</span> Check out the subgroup correlations<a href="regression-and-correlation.html#check-out-the-subgroup-correlations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For <strong>men</strong>, we can obtain the correlation between a1/e1 with the code below. From this we determine, <em>r</em> = .14, 95% [.07, .20], <em>p</em> &lt; .001.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="regression-and-correlation.html#cb343-1" tabindex="-1"></a><span class="fu">cor.test</span>(bfi_men<span class="sc">$</span>a1, bfi_men<span class="sc">$</span>e1)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  bfi_men$a1 and bfi_men$e1
## t = 4.2, df = 910, p-value = 3e-05
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.07448 0.20182
## sample estimates:
##    cor 
## 0.1387</code></pre>
<p>For <strong>women</strong>, we can obtain the correlation between a1/e1 with the code below. From this we determine, <em>r</em> = .06, 95% [.02, .11], <em>p</em> = .007.</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="regression-and-correlation.html#cb345-1" tabindex="-1"></a><span class="fu">cor.test</span>(bfi_women<span class="sc">$</span>a1, bfi_women<span class="sc">$</span>e1)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  bfi_women$a1 and bfi_women$e1
## t = 2.7, df = 1847, p-value = 0.007
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.01672 0.10754
## sample estimates:
##     cor 
## 0.06226</code></pre>
</div>
<div id="comparison-ra1-e1" class="section level4 hasAnchor" number="8.3.3.3">
<h4><span class="header-section-number">8.3.3.3</span> Comparison r(a1, e1)<a href="regression-and-correlation.html#comparison-ra1-e1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We run the R commands below to compare the correlations for men and women.</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="regression-and-correlation.html#cb347-1" tabindex="-1"></a><span class="fu">library</span>(cocor)</span>
<span id="cb347-2"><a href="regression-and-correlation.html#cb347-2" tabindex="-1"></a>bfi_men_dataframe   <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(bfi_men)</span>
<span id="cb347-3"><a href="regression-and-correlation.html#cb347-3" tabindex="-1"></a>bfi_women_dataframe <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(bfi_women)</span>
<span id="cb347-4"><a href="regression-and-correlation.html#cb347-4" tabindex="-1"></a></span>
<span id="cb347-5"><a href="regression-and-correlation.html#cb347-5" tabindex="-1"></a><span class="fu">cocor</span>( <span class="sc">~</span> a1 <span class="sc">+</span> e1 <span class="sc">|</span> a1 <span class="sc">+</span> e1,</span>
<span id="cb347-6"><a href="regression-and-correlation.html#cb347-6" tabindex="-1"></a>       <span class="at">data =</span> <span class="fu">list</span>(bfi_men_dataframe, bfi_women_dataframe))</span></code></pre></div>
<pre><code>## 
##   Results of a comparison of two correlations based on independent groups
## 
## Comparison between r1.jk (a1, e1) = 0.1387 and r2.hm (a1, e1) = 0.0623
## Difference: r1.jk - r2.hm = 0.0765
## Data: list(bfi_men_dataframe, bfi_women_dataframe): j = a1, k = e1, h = a1, m = e1
## Group sizes: n1 = 912, n2 = 1849
## Null hypothesis: r1.jk is equal to r2.hm
## Alternative hypothesis: r1.jk is not equal to r2.hm (two-sided)
## Alpha: 0.05
## 
## fisher1925: Fisher&#39;s z (1925)
##   z = 1.9074, p-value = 0.0565
##   Null hypothesis retained
## 
## zou2007: Zou&#39;s (2007) confidence interval
##   95% confidence interval for r1.jk - r2.hm: -0.0021 0.1543
##   Null hypothesis retained (Interval includes 0)</code></pre>
<p>The output reveals the correlation for men, <span class="math inline">\(r_{(a1, e1)}\)</span> = 0.1387, .14 rounded, and women <span class="math inline">\(r_{(a1, e1)}\)</span>= 0.0623, .06 rounded, in the output. We also see the comparison: Difference: r1.jk - r2.hm = 0.0765. Finally, we see the zou2007 95% confidence interval: -.00 to .15.</p>
<p>We write this up as:</p>
<p>For men, there was a positive relation between agreeableness (a1) and extraversion (e1), <em>r</em> = .14, 95% [.07, .20], <em>p</em> &lt; .001, such that as agreeableness increased so did extraversion. Likewise, for women, there was a similar positive relation between agreeableness (a1) and extraversion (e1), <em>r</em> = .06, 95% [.02, .11], <em>p</em> = .007. We did not find a significant difference in the strength of these relations, <span class="math inline">\(\Delta\)</span><em>r</em> = .08, 95% CI [-.00, .15], <em>p</em> = .057.</p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="an-emphasis-on-workflow.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/08-correlation.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
