<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Samples | PSYC6060 Course Notes</title>
  <meta name="description" content="Course notes for PSYC 6060" />
  <meta name="generator" content="bookdown 0.19.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Samples | PSYC6060 Course Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course notes for PSYC 6060" />
  <meta name="github-repo" content="dstanley4/psyc6060bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Samples | PSYC6060 Course Notes" />
  
  <meta name="twitter:description" content="Course notes for PSYC 6060" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2020-07-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="populations.html"/>
<link rel="next" href="graphing.html"/>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-information-and-conventions"><i class="fa fa-check"></i>Software information and conventions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#create-an-account-at-r-studio-cloud"><i class="fa fa-check"></i><b>1.3</b> Create an account at R Studio Cloud</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#join-the-class-workspace"><i class="fa fa-check"></i><b>1.4</b> Join the class workspace</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.5</b> Exploring the R Studio Interface</a><ul>
<li class="chapter" data-level="1.5.1" data-path="introduction.html"><a href="introduction.html#console-panel"><i class="fa fa-check"></i><b>1.5.1</b> Console panel</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction.html"><a href="introduction.html#script-panel"><i class="fa fa-check"></i><b>1.5.2</b> Script Panel</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.6</b> Writing your first script</a><ul>
<li class="chapter" data-level="1.6.1" data-path="introduction.html"><a href="introduction.html#create-the-script-file"><i class="fa fa-check"></i><b>1.6.1</b> Create the script file</a></li>
<li class="chapter" data-level="1.6.2" data-path="introduction.html"><a href="introduction.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.6.2</b> Add a comment to your script</a></li>
<li class="chapter" data-level="1.6.3" data-path="introduction.html"><a href="introduction.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.6.3</b> Background about the tidyverse</a></li>
<li class="chapter" data-level="1.6.4" data-path="introduction.html"><a href="introduction.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.6.4</b> Add library(tidyverse) to your script</a></li>
<li class="chapter" data-level="1.6.5" data-path="introduction.html"><a href="introduction.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.6.5</b> Activate tidyverse auto-complete for your script</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#loading-your-data"><i class="fa fa-check"></i><b>1.7</b> Loading your data</a><ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.7.1</b> Use read_csv (not read.csv) to open files.</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.8</b> Checking out your data</a><ul>
<li class="chapter" data-level="1.8.1" data-path="introduction.html"><a href="introduction.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.8.1</b> view(): See a spreadsheet view of your data</a></li>
<li class="chapter" data-level="1.8.2" data-path="introduction.html"><a href="introduction.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.8.2</b> print(): See you data in the Console</a></li>
<li class="chapter" data-level="1.8.3" data-path="introduction.html"><a href="introduction.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.8.3</b> head(): Check out the first few rows of data</a></li>
<li class="chapter" data-level="1.8.4" data-path="introduction.html"><a href="introduction.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.8.4</b> tail(): Check out the last few rows of data</a></li>
<li class="chapter" data-level="1.8.5" data-path="introduction.html"><a href="introduction.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.8.5</b> summary(): Quick summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.9</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source</a><ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#run-select-text"><i class="fa fa-check"></i><b>1.9.1</b> Run select text</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#source-without-echo"><i class="fa fa-check"></i><b>1.9.2</b> Source (without Echo)</a></li>
<li class="chapter" data-level="1.9.3" data-path="introduction.html"><a href="introduction.html#source-with-echo"><i class="fa fa-check"></i><b>1.9.3</b> Source with Echo</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.10</b> Trying Source with Echo</a></li>
<li class="chapter" data-level="1.11" data-path="introduction.html"><a href="introduction.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.11</b> A few key points about</a><ul>
<li class="chapter" data-level="1.11.1" data-path="introduction.html"><a href="introduction.html#lists"><i class="fa fa-check"></i><b>1.11.1</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="introduction.html"><a href="introduction.html#thats-it"><i class="fa fa-check"></i><b>1.12</b> That’s it!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required</a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective</a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console</a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.4</b> Basic tidyverse commands</a><ul>
<li class="chapter" data-level="2.4.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.4.1</b> select()</a></li>
<li class="chapter" data-level="2.4.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.4.2</b> summarise()</a></li>
<li class="chapter" data-level="2.4.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.4.3</b> filter()</a></li>
<li class="chapter" data-level="2.4.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.4.4</b> group_by()</a></li>
<li class="chapter" data-level="2.4.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.4.5</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Advanced tidyverse commands</a><ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.5.1</b> select()</a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.5.2</b> summarise()</a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.5.3</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.6</b> Using help</a></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.7</b> Base R vs tidyverse</a><ul>
<li class="chapter" data-level="2.7.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.7.1</b> Tibbles vs. data frames</a></li>
<li class="chapter" data-level="2.7.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.7.2</b> read.csv() and data frames</a></li>
<li class="chapter" data-level="2.7.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.7.3</b> read_csv() and tibbles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html"><i class="fa fa-check"></i><b>3</b> Making your data ready for analysis</a><ul>
<li class="chapter" data-level="3.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#required-packages"><i class="fa fa-check"></i><b>3.1</b> Required Packages</a></li>
<li class="chapter" data-level="3.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#objective-1"><i class="fa fa-check"></i><b>3.2</b> Objective</a></li>
<li class="chapter" data-level="3.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#context"><i class="fa fa-check"></i><b>3.3</b> Context</a></li>
<li class="chapter" data-level="3.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#begin-with-the-end-in-mind"><i class="fa fa-check"></i><b>3.4</b> Begin with the end in mind</a><ul>
<li class="chapter" data-level="3.4.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#structuring-data-obtaining-tidy-data"><i class="fa fa-check"></i><b>3.4.1</b> Structuring data: Obtaining tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#data-collection-considerations"><i class="fa fa-check"></i><b>3.5</b> Data collection considerations</a><ul>
<li class="chapter" data-level="3.5.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#naming-conventions"><i class="fa fa-check"></i><b>3.5.1</b> Naming conventions</a></li>
<li class="chapter" data-level="3.5.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#likert-type-items"><i class="fa fa-check"></i><b>3.5.2</b> Likert-type items</a></li>
<li class="chapter" data-level="3.5.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#anova-between"><i class="fa fa-check"></i><b>3.5.3</b> ANOVA between</a></li>
<li class="chapter" data-level="3.5.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#anova-within"><i class="fa fa-check"></i><b>3.5.4</b> ANOVA within</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#following-the-examples"><i class="fa fa-check"></i><b>3.6</b> Following the examples</a></li>
<li class="chapter" data-level="3.7" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#entering-data-into-spreadsheets"><i class="fa fa-check"></i><b>3.7</b> Entering data into spreadsheets</a></li>
<li class="chapter" data-level="3.8" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#experiment-between"><i class="fa fa-check"></i><b>3.8</b> Experiment: Between</a><ul>
<li class="chapter" data-level="3.8.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors"><i class="fa fa-check"></i><b>3.8.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.8.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening"><i class="fa fa-check"></i><b>3.8.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.8.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening"><i class="fa fa-check"></i><b>3.8.3</b> Numeric screening</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#experiment-within-one-way"><i class="fa fa-check"></i><b>3.9</b> Experiment: Within one-way</a><ul>
<li class="chapter" data-level="3.9.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-1"><i class="fa fa-check"></i><b>3.9.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.9.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-1"><i class="fa fa-check"></i><b>3.9.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.9.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-1"><i class="fa fa-check"></i><b>3.9.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.9.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#pivot-to-tidy-data"><i class="fa fa-check"></i><b>3.9.4</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#experiment-within-n-way"><i class="fa fa-check"></i><b>3.10</b> Experiment: Within N-way</a><ul>
<li class="chapter" data-level="3.10.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-2"><i class="fa fa-check"></i><b>3.10.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.10.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-2"><i class="fa fa-check"></i><b>3.10.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.10.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-2"><i class="fa fa-check"></i><b>3.10.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.10.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#pivot-to-tidy-data-1"><i class="fa fa-check"></i><b>3.10.4</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#surveys-single-occassion"><i class="fa fa-check"></i><b>3.11</b> Surveys: Single Occassion</a><ul>
<li class="chapter" data-level="3.11.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-3"><i class="fa fa-check"></i><b>3.11.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.11.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-3"><i class="fa fa-check"></i><b>3.11.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.11.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-3"><i class="fa fa-check"></i><b>3.11.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.11.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#scale-scores"><i class="fa fa-check"></i><b>3.11.4</b> Scale scores</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#surveys-multiple-occasions"><i class="fa fa-check"></i><b>3.12</b> Surveys: Multiple Occasions</a><ul>
<li class="chapter" data-level="3.12.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-4"><i class="fa fa-check"></i><b>3.12.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.12.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-4"><i class="fa fa-check"></i><b>3.12.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.12.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-4"><i class="fa fa-check"></i><b>3.12.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.12.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#scale-scores-1"><i class="fa fa-check"></i><b>3.12.4</b> Scale scores</a></li>
<li class="chapter" data-level="3.12.5" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#pivot-to-tidy-data-2"><i class="fa fa-check"></i><b>3.12.5</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.13" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#basic-descriptive-statistics"><i class="fa fa-check"></i><b>3.13</b> Basic descriptive statistics</a><ul>
<li class="chapter" data-level="3.13.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#skim"><i class="fa fa-check"></i><b>3.13.1</b> skim()</a></li>
<li class="chapter" data-level="3.13.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#apa.cor.table"><i class="fa fa-check"></i><b>3.13.2</b> apa.cor.table()</a></li>
<li class="chapter" data-level="3.13.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#tidyverse"><i class="fa fa-check"></i><b>3.13.3</b> tidyverse</a></li>
<li class="chapter" data-level="3.13.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#cronbachs-alpha"><i class="fa fa-check"></i><b>3.13.4</b> Cronbach’s alpha</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="populations.html"><a href="populations.html"><i class="fa fa-check"></i><b>4</b> Populations</a><ul>
<li class="chapter" data-level="4.1" data-path="populations.html"><a href="populations.html#notation"><i class="fa fa-check"></i><b>4.1</b> Notation</a></li>
<li class="chapter" data-level="4.2" data-path="populations.html"><a href="populations.html#population-vs-samples"><i class="fa fa-check"></i><b>4.2</b> Population vs samples</a></li>
<li class="chapter" data-level="4.3" data-path="populations.html"><a href="populations.html#a-small-population"><i class="fa fa-check"></i><b>4.3</b> A small population</a><ul>
<li class="chapter" data-level="4.3.1" data-path="populations.html"><a href="populations.html#mean-mu"><i class="fa fa-check"></i><b>4.3.1</b> Mean (<span class="math inline">\(\mu\)</span>)</a></li>
<li class="chapter" data-level="4.3.2" data-path="populations.html"><a href="populations.html#variance-sigma2"><i class="fa fa-check"></i><b>4.3.2</b> Variance (<span class="math inline">\(\sigma^2\)</span>)</a></li>
<li class="chapter" data-level="4.3.3" data-path="populations.html"><a href="populations.html#standard-deviation-sigma"><i class="fa fa-check"></i><b>4.3.3</b> Standard Deviation (<span class="math inline">\(\sigma\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="populations.html"><a href="populations.html#visualizing-populations"><i class="fa fa-check"></i><b>4.4</b> Visualizing populations</a></li>
<li class="chapter" data-level="4.5" data-path="populations.html"><a href="populations.html#population-comparisons"><i class="fa fa-check"></i><b>4.5</b> Population comparisons</a><ul>
<li class="chapter" data-level="4.5.1" data-path="populations.html"><a href="populations.html#standardized-units"><i class="fa fa-check"></i><b>4.5.1</b> Standardized units</a></li>
<li class="chapter" data-level="4.5.2" data-path="populations.html"><a href="populations.html#cohens-d-units"><i class="fa fa-check"></i><b>4.5.2</b> Cohen’s <span class="math inline">\(d\)</span> units</a></li>
<li class="chapter" data-level="4.5.3" data-path="populations.html"><a href="populations.html#cohens-d-advantages"><i class="fa fa-check"></i><b>4.5.3</b> Cohen’s <span class="math inline">\(d\)</span> advantages</a></li>
<li class="chapter" data-level="4.5.4" data-path="populations.html"><a href="populations.html#cohens-d-caveats"><i class="fa fa-check"></i><b>4.5.4</b> Cohen’s <span class="math inline">\(d\)</span> caveats</a></li>
<li class="chapter" data-level="4.5.5" data-path="populations.html"><a href="populations.html#benchmarks"><i class="fa fa-check"></i><b>4.5.5</b> Benchmarks</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="populations.html"><a href="populations.html#key-points"><i class="fa fa-check"></i><b>4.6</b> Key points</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="samples.html"><a href="samples.html"><i class="fa fa-check"></i><b>5</b> Samples</a><ul>
<li class="chapter" data-level="5.1" data-path="samples.html"><a href="samples.html#overview"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="samples.html"><a href="samples.html#data-for-the-chapter"><i class="fa fa-check"></i><b>5.2</b> Data for the chapter</a></li>
<li class="chapter" data-level="5.3" data-path="samples.html"><a href="samples.html#notation-1"><i class="fa fa-check"></i><b>5.3</b> Notation</a></li>
<li class="chapter" data-level="5.4" data-path="samples.html"><a href="samples.html#estimating-the-mean"><i class="fa fa-check"></i><b>5.4</b> Estimating the mean</a></li>
<li class="chapter" data-level="5.5" data-path="samples.html"><a href="samples.html#estimating-variance"><i class="fa fa-check"></i><b>5.5</b> Estimating variance</a></li>
<li class="chapter" data-level="5.6" data-path="samples.html"><a href="samples.html#estimating-standard-deviation"><i class="fa fa-check"></i><b>5.6</b> Estimating standard deviation</a></li>
<li class="chapter" data-level="5.7" data-path="samples.html"><a href="samples.html#estimating-smd"><i class="fa fa-check"></i><b>5.7</b> Estimating SMD</a><ul>
<li class="chapter" data-level="5.7.1" data-path="samples.html"><a href="samples.html#pooled-standard-deviation"><i class="fa fa-check"></i><b>5.7.1</b> Pooled standard deviation</a></li>
<li class="chapter" data-level="5.7.2" data-path="samples.html"><a href="samples.html#calculating-d"><i class="fa fa-check"></i><b>5.7.2</b> Calculating <span class="math inline">\(d\)</span></a></li>
<li class="chapter" data-level="5.7.3" data-path="samples.html"><a href="samples.html#assessing-bias"><i class="fa fa-check"></i><b>5.7.3</b> Assessing bias</a></li>
<li class="chapter" data-level="5.7.4" data-path="samples.html"><a href="samples.html#illustrating-variability"><i class="fa fa-check"></i><b>5.7.4</b> Illustrating variability</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="samples.html"><a href="samples.html#overview-1"><i class="fa fa-check"></i><b>5.8</b> Overview</a></li>
<li class="chapter" data-level="5.9" data-path="samples.html"><a href="samples.html#meta-analysis"><i class="fa fa-check"></i><b>5.9</b> Meta-analysis</a></li>
<li class="chapter" data-level="5.10" data-path="samples.html"><a href="samples.html#key-points-1"><i class="fa fa-check"></i><b>5.10</b> Key Points</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>6</b> Graphing</a><ul>
<li class="chapter" data-level="6.1" data-path="graphing.html"><a href="graphing.html#required-1"><i class="fa fa-check"></i><b>6.1</b> Required</a></li>
<li class="chapter" data-level="6.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>6.2</b> Data</a></li>
<li class="chapter" data-level="6.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>6.3</b> Graph basics</a></li>
<li class="chapter" data-level="6.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>6.4</b> Graphing efficiently</a></li>
<li class="chapter" data-level="6.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>6.5</b> Aesthetics</a><ul>
<li class="chapter" data-level="6.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>6.5.1</b> Fill color</a></li>
<li class="chapter" data-level="6.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>6.5.2</b> Overriding aes()</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>6.6</b> APA style</a></li>
<li class="chapter" data-level="6.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>6.7</b> Axes</a><ul>
<li class="chapter" data-level="6.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>6.7.1</b> Range</a></li>
<li class="chapter" data-level="6.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>6.7.2</b> Ticks</a></li>
<li class="chapter" data-level="6.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>6.7.3</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>6.8</b> Axis values</a><ul>
<li class="chapter" data-level="6.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>6.8.1</b> Text</a></li>
<li class="chapter" data-level="6.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>6.8.2</b> Angle</a></li>
<li class="chapter" data-level="6.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>6.8.3</b> Alignment</a></li>
<li class="chapter" data-level="6.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>6.8.4</b> Order</a></li>
<li class="chapter" data-level="6.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>6.8.5</b> Legend order</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>6.9</b> Custom colours</a><ul>
<li class="chapter" data-level="6.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>6.9.1</b> R palette</a></li>
<li class="chapter" data-level="6.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>6.9.2</b> Hex colours</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>6.10</b> Emoji</a><ul>
<li class="chapter" data-level="6.10.1" data-path="graphing.html"><a href="graphing.html#installation"><i class="fa fa-check"></i><b>6.10.1</b> Installation</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>6.11</b> Saving</a><ul>
<li class="chapter" data-level="6.11.1" data-path="graphing.html"><a href="graphing.html#mac"><i class="fa fa-check"></i><b>6.11.1</b> MAC</a></li>
<li class="chapter" data-level="6.11.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>6.11.2</b> PC or MAC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>7</b> Hypotheses</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="more-to-say.html"><a href="more-to-say.html"><i class="fa fa-check"></i><b>A</b> More to Say</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC6060 Course Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="samples" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Samples</h1>
<p>The following CRAN packages must be installed:</p>
<table>
<thead>
<tr class="header">
<th>Required CRAN Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
</tr>
<tr class="even">
<td>remotes</td>
</tr>
</tbody>
</table>
<p>The following GitHub packages must be installed:</p>
<table>
<thead>
<tr class="header">
<th>Required GitHub Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>dstanley4/learnSampling</td>
</tr>
</tbody>
</table>
<p>A GitHub package can be installed using the code below:</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="samples.html#cb313-1"></a>remotes<span class="op">::</span><span class="kw">install_github</span>(<span class="st">&quot;dstanley4/learnsampling&quot;</span>)</span></code></pre></div>
<div id="overview" class="section level2">
<h2><span class="header-section-number">5.1</span> Overview</h2>
<p>Researchers are usually interested in describing the attributes of a population; numbers that describe the population are called parameters. Two parameters that are frequently of interest are the mean and variance of the population. Unfortunately, it’s rarely possible to obtain information from every member of a population to calculate a parameter. Consequently, researchers use subsets of the population called samples to estimate parameters. Numbers calculated from sample data are called statistics. Typically, sample statistics are used to estimate population parameters.</p>
<p>Sample statistics, however, often differ from population parameters. The difference between a sample statistic and the population parameter occurs because the sample data is random subset of the population data — with correspondingly fewer observations. Sometimes the sample statistic will be higher than the population parameter; other times the sample statistic will be lower than the population parameter. Because random sampling is used to select the sample data the direction and magnitude of the difference between the sample statistic the population parameter will vary randomly.</p>
<p>Further complicating matters is the fact that the formula used for a sample statistic may, or may not, be the same as the formula used for the corresponding population parameter. This occurs because the purpose of the sample statistic is typically not to describe the sample. Rather the purpose of the sample statistic is to estimate the population parameter. Depending on the parameter, you may or may not be able to use the same formula with sample data as you would with population data.</p>
</div>
<div id="data-for-the-chapter" class="section level2">
<h2><span class="header-section-number">5.2</span> Data for the chapter</h2>
<p>We begin by activating the required packages:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="samples.html#cb314-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb314-2"><a href="samples.html#cb314-2"></a><span class="kw">library</span>(learnSampling)</span></code></pre></div>
<p>Next, we create a large population with 100,000 people using the get_height_population() command:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="samples.html#cb315-1"></a>pop_data &lt;-<span class="st"> </span><span class="kw">get_height_population</span>() </span></code></pre></div>
<p>The glimpse() command can be used to confirm that the population contains 100,000 people.</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="samples.html#cb316-1"></a><span class="kw">glimpse</span>(pop_data)</span></code></pre></div>
<pre><code>## Rows: 100,000
## Columns: 3
## $ id     &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,…
## $ sex    &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;female&quot;, &quot;male&quot;, &quot;male&quot;…
## $ height &lt;dbl&gt; 177, 150, 171, 157, 169, 187, 163, 173, 17…</code></pre>
<p>We can use the head() command to see the first 10 rows of the 100,00 rows. We see that each row in pop_data represents a single person.</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="samples.html#cb318-1"></a><span class="kw">head</span>(pop_data, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##       id sex    height
##    &lt;int&gt; &lt;chr&gt;   &lt;dbl&gt;
##  1     1 male      177
##  2     2 female    150
##  3     3 female    171
##  4     4 male      157
##  5     5 male      169
##  6     6 male      187
##  7     7 female    163
##  8     8 male      173
##  9     9 female    172
## 10    10 male      193</code></pre>
</div>
<div id="notation-1" class="section level2">
<h2><span class="header-section-number">5.3</span> Notation</h2>
<p>In the formulas below, when we refer the population, we use uppercase letters to indicate members (<span class="math inline">\(X\)</span>) or the size (<span class="math inline">\(N\)</span>). In contrast, when we refer to the sample, we use lowercase letters to indicate members (<span class="math inline">\(x\)</span>) or the size (<span class="math inline">\(n\)</span>). Make sure you notice the similarities between population and sample formulas even when the notation differs.</p>
</div>
<div id="estimating-the-mean" class="section level2">
<h2><span class="header-section-number">5.4</span> Estimating the mean</h2>
<p>We are interested in the sample mean (<span class="math inline">\(\bar{x}\)</span>) to the extent that it provides an estimate of the population mean (<span class="math inline">\(\mu\)</span>). The population mean is calculated using Formula <a href="samples.html#eq:popmeanch5">(5.1)</a>:</p>
<p><span class="math display" id="eq:popmeanch5">\[\begin{equation} 
\mu = \frac{\sum{X}}{N}
      \tag{5.1}
\end{equation}\]</span></p>
<p>We can calculate the population mean for the height column of pop_data using the summarise() and mean() commands. The mean() command uses Formula <a href="samples.html#eq:popmeanch5">(5.1)</a>. We see in the output that the population mean is 172.48 (<span class="math inline">\(\mu = 172.48\)</span>).</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="samples.html#cb320-1"></a>pop_data <span class="op">%&gt;%</span></span>
<span id="cb320-2"><a href="samples.html#cb320-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">pop_mean =</span> <span class="kw">mean</span>(height)) <span class="op">%&gt;%</span></span>
<span id="cb320-3"><a href="samples.html#cb320-3"></a><span class="st">  </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   pop_mean
## 1    172.5</code></pre>
<p>As noted previously, we rarely have access to data from an entire population. Consequently, we use the sample mean as an estimate of the population mean. The sample mean, <span class="math inline">\(\bar{x}\)</span>, is a statistic calculated using the using Formula <a href="samples.html#eq:samplemeanch5">(5.2)</a> below. The bar of above the <span class="math inline">\(x\)</span>, indicates that it is a mean. Notice that Formula <a href="samples.html#eq:popmeanch5">(5.1)</a> and Formula <a href="samples.html#eq:samplemeanch5">(5.2)</a> are the same - even though they use different notation.</p>
<p><span class="math display" id="eq:samplemeanch5">\[\begin{equation} 
\bar{x} = \frac{\sum{x}}{n}
      \tag{5.2}
\end{equation}\]</span></p>
<p>Because a sample mean (a statistic) is calculated using a random subset of the population it is likely to differ from the population mean (a parameter). If you, inaccurately, believe that you can learn something meaningful from a single study, this fact may be disconcerting. Statisticians know, however, that rarely can you learn anything from a single study, or even a small set of studies. Consequently, they are more interested in what is true, on average, over a large number of studies. Therefore, we simulate drawing a large number of samples from a population with the code below.</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="samples.html#cb322-1"></a>many_samples &lt;-<span class="st"> </span><span class="kw">get_M_samples</span>(<span class="dt">pop.data =</span> pop_data, </span>
<span id="cb322-2"><a href="samples.html#cb322-2"></a>                              <span class="dt">pop.column.name =</span> height,</span>
<span id="cb322-3"><a href="samples.html#cb322-3"></a>                              <span class="dt">n =</span> <span class="dv">10</span>,</span>
<span id="cb322-4"><a href="samples.html#cb322-4"></a>                              <span class="dt">number.of.samples =</span> <span class="dv">5000</span>)</span></code></pre></div>
<p>We use the head() command to see the first 10 rows (i.e., 10 samples of 5000 samples):</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="samples.html#cb323-1"></a><span class="kw">head</span>(many_samples, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    study  n sample.mean sample.var.n sample.var.n_1
## 1      1 10       174.3        27.81          30.90
## 2      2 10       161.8        83.36          92.62
## 3      3 10       173.2       139.16         154.62
## 4      4 10       180.0       321.80         357.56
## 5      5 10       172.8       160.96         178.84
## 6      6 10       172.0       159.60         177.33
## 7      7 10       166.5        86.45          96.06
## 8      8 10       173.5       139.45         154.94
## 9      9 10       177.7       167.01         185.57
## 10    10 10       168.5       262.65         291.83</code></pre>
<p>Each row of many_samples represents a sample of 10 people. Each column of many_samples indicates a sample statistic. You can see that for each sample/row we indicate “n” (the sample size) and “sample.mean” (the mean of the population), and a few other statistics. Even though all the samples came from the same population you can see how the values in the sample.mean column vary across samples/rows. You can see the full extent to which the sample means vary by creating a graph with the code below. In this code, we use the pull() command to extract the value from the sample.mean column and then we send them to the base R hisogram command, hist().</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="samples.html#cb325-1"></a>many_samples <span class="op">%&gt;%</span></span>
<span id="cb325-2"><a href="samples.html#cb325-2"></a><span class="st"> </span><span class="kw">pull</span>(sample.mean) <span class="op">%&gt;%</span></span>
<span id="cb325-3"><a href="samples.html#cb325-3"></a><span class="st"> </span><span class="kw">hist</span>(<span class="dt">main =</span> <span class="st">&quot;Histogram of Sample Means&quot;</span>)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-217-1.png" width="672" /></p>
<p>You can see the 5000 sample means, from the sample.mean column, plotted in this graph. Recall the population mean for heights is <span class="math inline">\(\mu = 172.48\)</span> cm. Notice that most of the sample means cluster around this value. Also notice there is considerable variability about this value. Any given sample mean (<span class="math inline">\(\bar{x}\)</span>) may differ substantially from the population mean (<span class="math inline">\(\mu = 172.48\)</span>). This variability illustrates the challenges with learning something from a single study - particularly a study with a small sample size. Many of the sample means fall quite far from the population mean.</p>
<p>Statisticians, recognizing the limitations of a single study, are not particularly concerned if a single sample mean deviates from the population mean. That said, statisticians are very concerned as to whether or not the results of a large number of studies are correct – on average. That is, does the average of many sample means correspond to the population mean. If, on average, the sample mean is accurate we refer to it as an unbiased estimator.</p>
<p>In the code below we calculate the average of the 5000 sample means to determine if the sample mean is an unbiased estimator.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="samples.html#cb326-1"></a>many_samples <span class="op">%&gt;%</span></span>
<span id="cb326-2"><a href="samples.html#cb326-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_of_sample.mean =</span> <span class="kw">mean</span>(sample.mean)) <span class="op">%&gt;%</span></span>
<span id="cb326-3"><a href="samples.html#cb326-3"></a><span class="st">  </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   mean_of_sample.mean
## 1               172.4</code></pre>
<p>We find that the average of the 5000 sample means is 172.41 which is very close to the population mean of 172.48. Note that when we did this, we used the same formula to calculate the sample mean (Formula <a href="samples.html#eq:samplemeanch5">(5.2)</a>) as we did the population mean (Formula <a href="samples.html#eq:popmeanch5">(5.1)</a>), although the notations differed. The average of the sample means was not identical to the population mean but it was very close - it would have been exactly the same with many more samples. Consequently, the sample mean provides an unbiased estimate of the population mean. In other words, it makes sense to use the sample mean as an estimate of the population mean. If we try to estimate the population mean with a sample mean we will, on average, be correct; although any given sample/study mean might be “wrong”.</p>
</div>
<div id="estimating-variance" class="section level2">
<h2><span class="header-section-number">5.5</span> Estimating variance</h2>
<p>We are interested in the sample variance (<span class="math inline">\(s^2\)</span>) to the extent that it provides an estimate of the population variance (<span class="math inline">\(\sigma^2\)</span>). We begin by reviewing population variance. The population variance is calculated using Formula <a href="samples.html#eq:popvarch5">(5.3)</a>:</p>
<p><span class="math display" id="eq:popvarch5">\[\begin{equation} 
\sigma^2 = \frac{\sum{(X - \mu)^2}}{N}
      \tag{5.3}
\end{equation}\]</span></p>
<p>We can calculate the population variance for the height column of pop_data using the summarise() and var.pop() commands. The var.pop() command uses Formula <a href="samples.html#eq:popvarch5">(5.3)</a>. We see in the output that the population variance is 157.5 (<span class="math inline">\(\sigma^2 = 157.5\)</span>).</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="samples.html#cb328-1"></a>pop_data <span class="op">%&gt;%</span></span>
<span id="cb328-2"><a href="samples.html#cb328-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">pop_var =</span> <span class="kw">var.pop</span>(height)) <span class="op">%&gt;%</span></span>
<span id="cb328-3"><a href="samples.html#cb328-3"></a><span class="st">  </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   pop_var
## 1   157.5</code></pre>
<p>Because we rarely have access to data for an entire population we typically want to estimate the population variance using sample data. However, estimating the population parameter from a statistic, is more complicated for variance than it was for the mean. Initially, we might be tempted to use the formula below for sample variance, in which we divide by <span class="math inline">\(n\)</span>. This formula is the same as the population variance formula, Formula <a href="samples.html#eq:popvarch5">(5.3)</a>, but adapted to use sample-level notation.</p>
<p><span class="math display">\[
\begin{aligned} 
s^2 = \frac{\sum{(x - \bar{x})^2}}{n}
\end{aligned} 
\]</span></p>
<p>The formula for sample variance with an <span class="math inline">\(n\)</span> in the denominator is, unfortunately, a biased estimator of population variance. That is, estimates of the population variance are systematically too low when you use a sample variance formula with an <span class="math inline">\(n\)</span> in the denominator. We can see that this is true by examining the many_samples data. In these data, the column sample.var.n contains the variance for the sample calculated with the above formula. Below we use code to obtain the average of the sample.var.n column over the 5000 samples. If this average equals the population variance of 157.5 then variance, using <span class="math inline">\(n\)</span> in the denominator, is an unbiased estimator of the population variance.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="samples.html#cb330-1"></a>many_samples <span class="op">%&gt;%</span></span>
<span id="cb330-2"><a href="samples.html#cb330-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_of_var.n =</span> <span class="kw">mean</span>(sample.var.n)) <span class="op">%&gt;%</span></span>
<span id="cb330-3"><a href="samples.html#cb330-3"></a><span class="st">  </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   mean_of_var.n
## 1         141.1</code></pre>
<p>You can see the average of sample.var.n column (141.86) is much smaller than the population variance (157.5). That is, the average of the sample variances, using <span class="math inline">\(n\)</span> in the denominator, was smaller than the population variance. Consequently, sample variance, using <span class="math inline">\(n\)</span> in the denominator, provides a biased estimate of the population variance. If we try to estimate the population variance with sample variance, using <span class="math inline">\(n\)</span> in the denominator, we will, on average, be wrong.</p>
<p>Fortunately, there is a sample-level formula that estimates the population variance without bias (see Hayes). An unbiased estimate of the population variance can be obtained if we calculate the sample variance but divide by <span class="math inline">\(n - 1\)</span> instead of <span class="math inline">\(n\)</span>. The unbiased estimate is calculated using Formula <a href="samples.html#eq:samplevarn1ch5">(5.4)</a>.</p>
<p><span class="math display" id="eq:samplevarn1ch5">\[\begin{equation} 
s^2 = \frac{\sum{(x - \bar{x})^2}}{n-1}
      \tag{5.4}
\end{equation}\]</span></p>
<p>In the many_samples data, the column sample.var.n_1 was generated using Formula <a href="samples.html#eq:samplevarn1ch5">(5.4)</a>. We can evaluate the quality of Formula <a href="samples.html#eq:samplevarn1ch5">(5.4)</a>, using <span class="math inline">\(n-1\)</span>, by averaging over values in the sample.var.n_1 column.</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="samples.html#cb332-1"></a>many_samples <span class="op">%&gt;%</span></span>
<span id="cb332-2"><a href="samples.html#cb332-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_of_var.n_1 =</span> <span class="kw">mean</span>(sample.var.n_<span class="dv">1</span>)) <span class="op">%&gt;%</span></span>
<span id="cb332-3"><a href="samples.html#cb332-3"></a><span class="st">  </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   mean_of_var.n_1
## 1           156.7</code></pre>
<p>We see that the average of the 5000 values using <span class="math inline">\(n-1\)</span> in the denominator is 157.62 which is very close to the population varaince of 157.46. Consequently, we when we use <span class="math inline">\(n-1\)</span> in the denominator we have an unbiased estimate of the population variance. If we try to estimate the population variance with a sample variance, using <span class="math inline">\(n-1\)</span> in the denominator, we will, on average, be right.</p>
<p>You may wonder at this point, when we use <span class="math inline">\(n-1\)</span> in the denominator of the sample variance, can we still think of it as the average of the squared deviations from the mean. The short answer is yes. When you use <span class="math inline">\(n-1\)</span> in the denominator of the sample variance you are not calculating the variance for the group people in the sample. Rather, you are estimating the variance for the much larger group of people in the population. Consequently, it makes sense to think of sample variance, using <span class="math inline">\(n-1\)</span>, as an estimate of the average of the squared errors <em>in the population</em>. That is, it makes sense to think of sample variance, using <span class="math inline">\(n-1\)</span>, as an estimate of the average of the squared differences between each person in the population and the population mean.</p>
</div>
<div id="estimating-standard-deviation" class="section level2">
<h2><span class="header-section-number">5.6</span> Estimating standard deviation</h2>
<p>The population standard deviation is calculated using Formula <a href="samples.html#eq:popsdch5">(5.5)</a> below.</p>
<p><span class="math display" id="eq:popsdch5">\[\begin{equation} 
\sigma = \sqrt{\frac{\sum{(X- \mu)^2}}{N}}
      \tag{5.5}
\end{equation}\]</span></p>
<p>Due to the above findings for variance, we estimate the population standard deviation using Formula <a href="samples.html#eq:samplesd1ch5">(5.6)</a> below.</p>
<p><span class="math display" id="eq:samplesd1ch5">\[\begin{equation} 
s = \sqrt{\frac{\sum{(x - \bar{x})^2}}{n-1}}
      \tag{5.6}
\end{equation}\]</span></p>
</div>
<div id="estimating-smd" class="section level2">
<h2><span class="header-section-number">5.7</span> Estimating SMD</h2>
<p>We are interested in the sample standardized mean difference (<span class="math inline">\(d\)</span>) to the extent that it provides an estimate of the population standardized mean difference (<span class="math inline">\(\delta\)</span>). The population standardized mean difference is calculated using Formula <a href="samples.html#eq:popsmdch5">(5.7)</a>:</p>
<p><span class="math display" id="eq:popsmdch5">\[\begin{equation} 
\delta  = \frac{\mu_{1} - \mu_{2}}{\sigma} 
      \tag{5.7}
\end{equation}\]</span></p>
<p>We can calculate the population standardized mean difference for men and women once we have the respective population means and standard deviations. Recall the initial data mixed males and females. We begin by creating separate data sets for males and females:</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="samples.html#cb334-1"></a>male_population_heights &lt;-<span class="st"> </span>pop_data <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb334-2"><a href="samples.html#cb334-2"></a><span class="st">  </span><span class="kw">filter</span>(sex <span class="op">==</span><span class="st"> &quot;male&quot;</span>) </span>
<span id="cb334-3"><a href="samples.html#cb334-3"></a></span>
<span id="cb334-4"><a href="samples.html#cb334-4"></a>female_population_heights &lt;-<span class="st"> </span>pop_data <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb334-5"><a href="samples.html#cb334-5"></a><span class="st">  </span><span class="kw">filter</span>(sex <span class="op">==</span><span class="st"> &quot;female&quot;</span>) </span></code></pre></div>
<p>Next, we calculate the mean and standard deviation of each population:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="samples.html#cb335-1"></a>male_population_heights <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb335-2"><a href="samples.html#cb335-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(height),</span>
<span id="cb335-3"><a href="samples.html#cb335-3"></a>            <span class="dt">sd =</span> <span class="kw">sd.pop</span>(height))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##    mean    sd
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  180.  10.1</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="samples.html#cb337-1"></a>female_population_heights <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb337-2"><a href="samples.html#cb337-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(height),</span>
<span id="cb337-3"><a href="samples.html#cb337-3"></a>            <span class="dt">sd =</span> <span class="kw">sd.pop</span>(height))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##    mean    sd
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  165.  10.1</code></pre>
<p>This reveals the population parameters are:</p>
<p><span class="math display">\[
\begin{aligned} 
\mu_{female} &amp;= 165 \\
\mu_{male} &amp;= 180 \\
\sigma = \sigma_{female} = \sigma_{male} &amp;= 10.1\\
\end{aligned} 
\]</span></p>
<p>Likewise, the population-level standardized mean difference (<span class="math inline">\(\delta\)</span>) is 1.49. We can see this population-level difference illustrated in Figure <a href="samples.html#fig:sexpop">5.1</a>.</p>
<p><span class="math display">\[
\begin{aligned} 
\delta  &amp;= \frac{\mu_{male} - \mu_{female}}{\sigma} \\
&amp;= \frac{180 - 165}{10.1} \\
&amp;= \frac{15}{10.1} \\
&amp;= 1.49 \\
\end{aligned} 
\]</span></p>
<div class="figure"><span id="fig:sexpop"></span>
<img src="ch_samples/images/sex_pops.png" alt="Illustration of the standardized mean difference of 1.49 for height between males and females. The solid black vertical lines indicates the means ($\mu$) for the two populations." width="95%" />
<p class="caption">
FIGURE 5.1: Illustration of the standardized mean difference of 1.49 for height between males and females. The solid black vertical lines indicates the means (<span class="math inline">\(\mu\)</span>) for the two populations.
</p>
</div>
<p>We typically need to estimate the population-level standardized mean difference from sample data because we rarely have access to data for an entire population. Many researchers estimate the population standardized mean difference from sample data using the Formula <a href="samples.html#eq:samplesmdch5">(5.8)</a> below. This value is known by many other names: <span class="math inline">\(d\)</span>, Cohen’s <span class="math inline">\(d\)</span>, and Hedges <span class="math inline">\(g\)</span>. Notice that the sample-level formula, Formula <a href="samples.html#eq:samplesmdch5">(5.8)</a>, below, is the same as the population-level formula, Formula <a href="samples.html#eq:popsmdch5">(5.7)</a>, above, only the notation differs.</p>
<p><span class="math display" id="eq:samplesmdch5">\[\begin{equation} 
d  = \frac{\bar{x}_{1} - \bar{x}_{2}}{s_{pooled}} 
      \tag{5.8}
\end{equation}\]</span></p>
<p>Unfortunately, Formula <a href="samples.html#eq:samplesmdch5">(5.8)</a> provides a biased estimate of the population standardized mean difference for small sample sizes. That is, on average, Formula <a href="samples.html#eq:samplesmdch5">(5.8)</a>, provides <span class="math inline">\(d\)</span>-values that overestimate the size of the population standardize mean difference (<span class="math inline">\(\delta\)</span>). Fortunately, we can obtain an unbiased estimate of the population-level standardized mean difference from sample data using Formula <a href="samples.html#eq:samplesmdunbiasedch5">(5.9)</a>.</p>
<p><span class="math display" id="eq:samplesmdunbiasedch5">\[\begin{equation} 
d_{unbiased}  = \frac{\bar{x}_{1} - \bar{x}_{2}}{s_{pooled}} \times [1 - \frac{3}{4(n_1 + n_2)-9}]
      \tag{5.9}
\end{equation}\]</span></p>
<p>If we try to apply either <span class="math inline">\(d\)</span>-value formula (<a href="samples.html#eq:samplesmdch5">(5.8)</a> or <a href="samples.html#eq:samplesmdunbiasedch5">(5.9)</a>) to real data we quickly encounter a problem. We don’t have the pooled standard deviation, <span class="math inline">\(s_{pooled}\)</span></p>
<div id="pooled-standard-deviation" class="section level3">
<h3><span class="header-section-number">5.7.1</span> Pooled standard deviation</h3>
<p>When we calculated the population-level standardized mean difference, there was only one standard deviation (i.e., only one variance). More specifically, the male and female populations both had a standard deviation but it was the same for both populations. The population-level formula for the standardized mean difference, Formula <a href="samples.html#eq:popsmdch5">(5.7)</a>, has only one standard deviation in it. This is because calculation of the standardized mean difference explicitly depends on the fact the both population have the same standard deviation.</p>
<p>Let’s consider hypothetical sample data to make the situation clear. More specifically, we will examine the sample-level statistics below for males and females. Notice that we have two standard deviations – one for males and one for females. Moreover, these two sample-level standard deviation (using <span class="math inline">\(n\)</span>-1) are not the same - they are different from each other. This initially seems problematic - calculation of standardized mean difference requires that population standard deviaitons are identical. Fortunately, this is sample-level data and not population-level data.</p>
<p><span class="math display">\[
\begin{aligned} 
\bar{x}_{males} &amp;= 187.2 \\
s_{males}^2 &amp;= 92.2 \\
s_{males} &amp;= 9.6 \\
\end{aligned} 
\]</span></p>
<p>And females:</p>
<p><span class="math display">\[
\begin{aligned} 
\bar{x}_{females} &amp;= 160.1 \\
s_{females}^2 &amp;= 66.8 \\
s_{females} &amp;= 8.2 \\
\end{aligned} 
\]</span></p>
<p>We need to recognize that the sample-level standard deviations are likely to differ from the population-level standard deviation due to sampling error. Consequently, we are likely to get two different sample-level standard deviations even if the population-level standard deviations are identical for males and females.</p>
<p>How do we resolve this situation of having two sample-level standard deviations? The first step is to switch to thinking in terms of variance rather than standard deviation. Due to the way the math works, life becomes very complicated, very quickly, if we continue to think in terms of standard deviations. Therefore, we reframe the problem into a variance problem. Variances are preferable to standard deviations because we can add and subtract variances - but not standard deviations.</p>
<p>We have a sample variance for males (92.2) and a sample variance for females (66.8). We view each of these sample variances as an estimate of the respective population variances (see Figure <a href="samples.html#fig:pool1">5.2</a>). That is, the male sample variance is an estimate of the male population variance. Likewise, the female sample variance is an estimate of the female population variance. However, we also <strong>assume</strong> that the population variances for males and females are the same. Consequently, the male sample variance and the female sample variance are both estimates of a single population variance (see Figure <a href="samples.html#fig:pool2">5.3</a>). Because the two sample variances are estimates of the same population variance, we can (when the sample sizes are equal) calculate a new variance by averaging them together. This new variance, the average of the sample variances, provides us with a better estimate of the single population variance. The logic behind this approach is similar to averaging two measurements of the same distance to reduce error. We call this new variance pooled variance; and represent it with the symbol <span class="math inline">\(s_{pooled}^2\)</span>.</p>
<div style="page-break-after: always;"></div>
<div class="figure"><span id="fig:pool1"></span>
<img src="ch_samples/images/pool1.png" alt="Estimating population variances with sample variances. The male sample variance (n-1) is an estimate of male population variance. Likewise, the female sample variance (n-1) is an estimate of the female population variance. " width="80%" />
<p class="caption">
FIGURE 5.2: Estimating population variances with sample variances. The male sample variance (n-1) is an estimate of male population variance. Likewise, the female sample variance (n-1) is an estimate of the female population variance.
</p>
</div>

<div class="figure"><span id="fig:pool2"></span>
<img src="ch_samples/images/pool2.png" alt="Two estimates of a single population variance. We assume the population variances are the same. Therefore, the male and female sample variances are both estimates of the same population variance." width="80%" />
<p class="caption">
FIGURE 5.3: Two estimates of a single population variance. We assume the population variances are the same. Therefore, the male and female sample variances are both estimates of the same population variance.
</p>
</div>
<div style="page-break-after: always;"></div>
<div class="figure"><span id="fig:pool3"></span>
<img src="ch_samples/images/pool3.png" alt="Pooled variance estimates population variance. We create a single estimate of the population variance called pooled variance ($s_{pooled}^2$). When sample sizes are equal, the pooled variance is just the average of the two sample variances (both using n-1). When the sample sizes are unequal (i.e., different numbers of males and females), we need to use a more sophisticated formula to obtain the pooled variance." width="80%" />
<p class="caption">
FIGURE 5.4: Pooled variance estimates population variance. We create a single estimate of the population variance called pooled variance (<span class="math inline">\(s_{pooled}^2\)</span>). When sample sizes are equal, the pooled variance is just the average of the two sample variances (both using n-1). When the sample sizes are unequal (i.e., different numbers of males and females), we need to use a more sophisticated formula to obtain the pooled variance.
</p>
</div>
<p>When the sample sizes for males and females are the same (i.e., <span class="math inline">\(n_{males} =n_{females}\)</span>) we can use the Formula <a href="samples.html#eq:poolvarequalch5">(5.10)</a> below to calculate the pooled variance.</p>
<p><span class="math display" id="eq:poolvarequalch5">\[\begin{equation} 
s_{pooled}^2  = \frac{s_{1}^2 + s_{2}^2}{2} 
      \tag{5.10}
\end{equation}\]</span></p>
<p>When the sample sizes for males and females are the different (i.e., <span class="math inline">\(n_{males} \ne n_{females}\)</span>) we can use the Formula <a href="samples.html#eq:poolvarch5">(5.11)</a> below to calculate the pooled variance. This formula can be used all of the time. We only show Formula <a href="samples.html#eq:poolvarequalch5">(5.10)</a>, above, to make it clear that Formula <a href="samples.html#eq:poolvarch5">(5.11)</a> below is basically just averaging the variances in a way that takes sample size into account.</p>
<p><span class="math display" id="eq:poolvarch5">\[\begin{equation} 
s_{pooled}^2  = \frac{(n_1 -1)s_1^2 + (n_2 -1)s_2^2}{n_1 + n_2-2}
      \tag{5.11}
\end{equation}\]</span></p>
<p>We get the single standard deviation we need, <span class="math inline">\(s_{pooled}\)</span>, by taking the square root of the variance, <span class="math inline">\(s_{pooled}^2\)</span>.</p>
<p><span class="math display">\[
\begin{aligned} 
s_{pooled}  &amp;= \sqrt{s_{pooled}^2} \\
\end{aligned} 
\]</span></p>
<p>If we apply the pooled standard variance, Formula <a href="samples.html#eq:poolvarch5">(5.11)</a>, to the sample data:</p>
<p><span class="math display">\[
\begin{aligned}
s_{pooled}^2 &amp;= \frac{(n_{male} -1)s_{male}^2 + (n_{female} -1)s_{female}^2}{n_{male} + n_{female}-2} \\
&amp;= \frac{(10 -1)92.2 + (10 -1)66.8}{10 + 10 -2} \\
&amp;= 79.5
\end{aligned}
\]</span></p>
<p>And then we obtain the pooled standard deviation we need, below, for the standardized mean difference formula.</p>
<p><span class="math display">\[
\begin{aligned} 
s_{pooled}  &amp;= \sqrt{79.5} \\
&amp;= 8.9\\
\end{aligned} 
\]</span></p>
</div>
<div id="calculating-d" class="section level3">
<h3><span class="header-section-number">5.7.2</span> Calculating <span class="math inline">\(d\)</span></h3>
<p>Now that we the pooled standard deviation, <span class="math inline">\(s_{pooled}\)</span>, we can calculated the standardized mean difference. We do so below using unbiased formula, Formula <a href="samples.html#eq:samplesmdunbiasedch5">(5.9)</a>.</p>
<p><span class="math display">\[
\begin{aligned}
d_{unbiased}  &amp;= d \times [1 - \frac{3}{4(n_{males} + n_{females})-9}] \\
&amp;= \frac{\bar{x}_{males} - \bar{x}_{females}}{s_{pooled}} \times [1 - \frac{3}{4(n_{males} + n_{females})-9}] \\
&amp;= \frac{187.2 - 160.1}{8.9} \times [1 - \frac{3}{4(10 + 10)-9}] \\
&amp;= 3.0 \times 0.96\\
&amp;= 2.9\\
\end{aligned}
\]</span></p>
</div>
<div id="assessing-bias" class="section level3">
<h3><span class="header-section-number">5.7.3</span> Assessing bias</h3>
<p>We can use our population-level data and sample from it to see the range of sample-level d-values that can occur.</p>
<p>First, we remove the scores from the male and female columns and place them into male_heights and female_heights, respectively.</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="samples.html#cb339-1"></a>male_heights &lt;-<span class="st"> </span>male_population_heights <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb339-2"><a href="samples.html#cb339-2"></a><span class="st">  </span><span class="kw">pull</span>(height)</span>
<span id="cb339-3"><a href="samples.html#cb339-3"></a></span>
<span id="cb339-4"><a href="samples.html#cb339-4"></a>female_heights &lt;-<span class="st"> </span>female_population_heights <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb339-5"><a href="samples.html#cb339-5"></a><span class="st">  </span><span class="kw">pull</span>(height)</span></code></pre></div>
<p>Next we obtain a large number of samples from each population and place them in many_samples.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="samples.html#cb340-1"></a>many_samples&lt;-<span class="st">  </span><span class="kw">get_d_samples_from_population_data</span>(<span class="dt">pop1 =</span> male_heights,</span>
<span id="cb340-2"><a href="samples.html#cb340-2"></a>                                   <span class="dt">pop2 =</span> female_heights,</span>
<span id="cb340-3"><a href="samples.html#cb340-3"></a>                                   <span class="dt">cell.n =</span> <span class="dv">10</span>,</span>
<span id="cb340-4"><a href="samples.html#cb340-4"></a>                                   <span class="dt">number.of.samples =</span> <span class="dv">5000</span>)</span></code></pre></div>
<p>We can example the contents of many_samples using the head() command. Each row of many_samples illustrates two samples: 10 males and 10 females. For both males and females we calculate the mean and variance. As well, we calcualte the <span class="math inline">\(d\)</span> and <span class="math inline">\(d_{unbiased}\)</span> for each row. If you examine the first row carefully you see that the data in this row corresponds to the hand calculation example.</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="samples.html#cb341-1"></a><span class="kw">head</span>(many_samples, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    study group.n    m1    m2     v1     v2 s2.1 s2.2    d
## 1      1      10 187.2 160.1  92.18  66.77 80.4 58.9 3.04
## 2      2      10 183.0 166.0 107.33  77.78 80.4 58.9 1.77
## 3      3      10 181.0 168.8  39.78 144.18 80.4 58.9 1.27
## 4      4      10 175.4 162.5  80.27  89.39 80.4 58.9 1.40
## 5      5      10 184.1 163.6  90.99  28.93 80.4 58.9 2.65
## 6      6      10 181.8 165.6  96.40 106.27 80.4 58.9 1.61
## 7      7      10 176.6 167.0  97.16 161.56 80.4 58.9 0.84
## 8      8      10 188.0 160.8 211.56 204.62 80.4 58.9 1.89
## 9      9      10 185.3 165.8  54.68  91.51 80.4 58.9 2.28
## 10    10      10 179.3 161.9  69.34  55.43 80.4 58.9 2.20
##    d.unbiased
## 1        2.91
## 2        1.69
## 3        1.22
## 4        1.34
## 5        2.54
## 6        1.54
## 7        0.81
## 8        1.81
## 9        2.18
## 10       2.11</code></pre>
<p>Recall the population level standardized mean difference, <span class="math inline">\(\delta\)</span>, was 1.49. We can see the extent to which the average the <span class="math inline">\(d\)</span> and <span class="math inline">\(d_{unbiased}\)</span> compare to this population-level values.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="samples.html#cb343-1"></a>many_samples <span class="op">%&gt;%</span></span>
<span id="cb343-2"><a href="samples.html#cb343-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_d =</span> <span class="kw">mean</span>(d),</span>
<span id="cb343-3"><a href="samples.html#cb343-3"></a>            <span class="dt">mean_d_unbiased =</span> <span class="kw">mean</span>(d.unbiased))</span></code></pre></div>
<pre><code>##   mean_d mean_d_unbiased
## 1  1.564           1.498</code></pre>
<p>You can see the mean of the <span class="math inline">\(d\)</span> values is 1.56 which is higher than the population-level standardize mean difference (<span class="math inline">\(\delta\)</span>). In contrast, you can see the mean of the <span class="math inline">\(d_{unbiased}\)</span> values is 1.498 which closely corresponds to the population-level standardize mean difference (<span class="math inline">\(\delta\)</span>) - it would have exactly corresponded with more samples.</p>
</div>
<div id="illustrating-variability" class="section level3">
<h3><span class="header-section-number">5.7.4</span> Illustrating variability</h3>
<p>An inspection of the first few rows of the the of many_samples data above illustrated that many of the <span class="math inline">\(d_{unbiased}\)</span> values differed from the population-level standardized mean difference of <span class="math inline">\(\delta = 1.49\)</span>. We can see the variability in sample-level <span class="math inline">\(d_{unbiased}\)</span> values in the histogram below.</p>
<div class="figure"><span id="fig:ddist"></span>
<img src="ch_samples/images/d_dist.png" alt="Histogram of $d_{unbiased}$ when $\delta = 1.49$" width="95%" />
<p class="caption">
FIGURE 5.5: Histogram of <span class="math inline">\(d_{unbiased}\)</span> when <span class="math inline">\(\delta = 1.49\)</span>
</p>
</div>
<p>We can calculate the full range of sample-level <span class="math inline">\(d_{unbiased}\)</span> values with the commands below:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="samples.html#cb345-1"></a>many_samples <span class="op">%&gt;%</span></span>
<span id="cb345-2"><a href="samples.html#cb345-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">d_min =</span> <span class="kw">min</span>(d.unbiased),</span>
<span id="cb345-3"><a href="samples.html#cb345-3"></a>            <span class="dt">d_max =</span> <span class="kw">max</span>(d.unbiased))</span></code></pre></div>
<pre><code>##   d_min d_max
## 1 -0.16  5.15</code></pre>
<p>We see from the output that <span class="math inline">\(d_{unbiased}\)</span> values were as small as -.20 and as large as 5.2. All of these values are estimates of the population level standardized mean difference of <span class="math inline">\(\delta = 1.49\)</span>. You can see that many of the sample-level estimates differed considerably from the population-level value. Indeed,</p>
</div>
</div>
<div id="overview-1" class="section level2">
<h2><span class="header-section-number">5.8</span> Overview</h2>
<p>In this chapter we have illustrated how a number of population parameter can be estimated by sample statistics. These are summarised below.</p>

<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Parameter</th>
<th>Estimated by this statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td><span class="math inline">\(\mu = \frac{\sum{X}}{N}\)</span></td>
<td><span class="math inline">\(\bar{x} = \frac{\sum{x}}{n}\)</span></td>
</tr>
<tr class="even">
<td>Variance</td>
<td><span class="math inline">\(\sigma^2 = \frac{\sum{(X - \mu)^2}}{N}\)</span></td>
<td><span class="math inline">\(s^2 = \frac{\sum{(x - \bar{x})^2}}{n-1}\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td><span class="math inline">\(s_{pooled}^2 = \frac{(n_1 -1)s_1^2 + (n_2 -1)s_2^2}{n_1 + n_2-2}\)</span></td>
</tr>
<tr class="even">
<td>Standard deviation</td>
<td><span class="math inline">\(\sigma = \sqrt{\frac{\sum{(X - \mu)^2}}{N}}\)</span></td>
<td><span class="math inline">\(s =\sqrt{\frac{\sum{(x - \bar{x})^2}}{n-1}}\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td><span class="math inline">\(s_{pooled} = \sqrt{\frac{(n_1 -1)s_1^2 + (n_2 -1)s_2^2}{n_1 + n_2-2}}\)</span></td>
</tr>
<tr class="even">
<td>Cohen’s <span class="math inline">\(d\)</span> or SMD</td>
<td><span class="math inline">\(\delta= \frac{\mu_{1} - \mu_{2}}{\sigma}\)</span></td>
<td><span class="math inline">\(d = \frac{\bar{x}_{1} - \bar{x}_{2}}{s_{pooled}}\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td><span class="math inline">\(d_{unbiased} = \frac{\bar{x}_{1} - \bar{x}_{2}}{s_{pooled}} \times [1 - \frac{3}{4(n_1 + n_2)-9}]\)</span></td>
</tr>
</tbody>
</table>

</div>
<div id="meta-analysis" class="section level2">
<h2><span class="header-section-number">5.9</span> Meta-analysis</h2>
<p>It may seem odd that we used so many simulations to investigate the properties of statistics. Surely, researchers don’t do that “in the real world”. In fact, researchers that are aware of the enormous impact of sampling error know single studies have little informational value. They recognize that any single study has a high probability of being misleading. Consequently, these individuals survey the literature and find all the studies on a single topic (possibly thousands of studies). An average of the results of all of the thousands of studies can then be calculated and reported. This process is refered to as conducting a meta-analysis; and it perfectly corresponds to the process we used in the simulations. A meta-analysis finds “the truth” of what is happening at the population level by averaging over all of the studies on that topic.</p>
</div>
<div id="key-points-1" class="section level2">
<h2><span class="header-section-number">5.10</span> Key Points</h2>
<ul>
<li><p>Sample are of interest because the help use estimate attribute of the population</p></li>
<li><p>Sample statistics estimate population parameters</p></li>
<li><p>Due to the fact that sample statistics are based on a random subset of the population (i.e., a sample) they often differ substantially from the population parameter. This illustrates that informational value of a single study is typically quite low.</p></li>
<li><p>A statistic is unbiased if the average of the sample statistics, over many thousand of samples, equals the population parameter.</p></li>
<li><p>To avoid bias, sometimes the formula for a sample statistics differs from the formula for the population parameter</p></li>
<li><p>We used simulations to but they were like a meta-analysis.</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="populations.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="graphing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/05-samples.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
